#!/usr/bin/env node
// 대량 확장: 미매핑 아이콘 단어에 한국어 추가 + 기존 항목 보강
const fs = require('fs');
const path = require('path');

const ko = JSON.parse(fs.readFileSync(path.join(__dirname,'..','ko_dict.json'),'utf8'));
const words = new Set(JSON.parse(fs.readFileSync(path.join(__dirname,'..','data','icon_words.json'),'utf8')).map(w=>w.word));
const v = (...arr) => arr.filter(w => words.has(w));

// ============================================================
// 추가할 한국어 → 영단어 매핑 (대규모 확장)
// ============================================================
const bulk = {

  // ━━━ 브랜드/앱/플랫폼 ━━━
  '피그마':       v('figma'),
  '슬랙':         v('slack'),
  '디스코드':     v('discord'),
  '노션':         v('notion'),
  '텔레그램':     v('telegram'),
  '왓츠앱':       v('whatsapp'),
  '틱톡':         v('tiktok'),
  '스냅챗':       v('snapchat'),
  '스포티파이':   v('spotify'),
  '핀터레스트':   v('pinterest'),
  '비핸스':       v('behance'),
  '드리블':       v('dribbble'),
  '깃랩':         v('gitlab'),
  '트렐로':       v('trello'),
  '슬랙채널':     v('slack'),
  '스카이프':     v('skype'),
  '줌':           v('zoom'),
  '페이팔':       v('paypal'),
  '알리페이':     v('alipay'),
  '위챗':         v('wechat','weixin'),
  '트위치':       v('twitch'),
  '텀블러':       v('tumblr'),
  '비메오':       v('vimeo'),
  '사운드클라우드':v('soundcloud'),
  '코드펜':       v('codepen'),
  '앵귤러':       v('angular'),
  '뷰':           v('vue'),
  '플러터':       v('flutter'),
  '리액트':       v('react'),
  '사스':         v('sass'),
  '타입스크립트': v('typescript'),
  '자바스크립트': v('javascript'),
  '파이썬':       v('python'),
  '자바':         v('java'),
  'PHP':          v('php'),
  '쿠버네티스':   v('kubernetes'),
  '도커':         v('docker'),
  '파이어베이스': v('firebase'),
  '아마존AWS':    v('aws'),
  '아이케아':     v('ikea'),
  '마스터카드':   v('mastercard'),
  '비자카드':     v('visa'),
  '이더리움':     v('ethereum'),
  '드롭박스':     v('dropbox'),
  '스택오버플로우':v('stackoverflow'),
  '마스토돈':     v('mastodon'),
  '패트리온':     v('patreon'),
  '핏빗':         v('fitbit'),
  '닌텐도':       v('nintendo'),
  '플레이스테이션':v('playstation'),
  'SVG':          v('svg'),
  'HTML':         v('html','html5'),
  'CSS':          v('css','css3'),
  'JSON':         v('json'),
  'PNG':          v('png'),
  'JPG':          v('jpg'),
  'GIF':          v('gif'),
  'CSV':          v('csv'),
  'PDF파일':      v('pdf'),
  'NPM':          v('npm'),
  'VS코드':       v('vscode'),
  '블렌더':       v('blender'),
  '포토샵':       v('photoshop'),
  '포스퀘어':     v('foursquare'),
  '워드프레스':   v('wordpress'),

  // ━━━ 통화/전화 상태 ━━━
  '통화중':       v('calling','call','phone','signal'),
  '부재중':       v('missed','call','phone'),
  '음성메일':     v('voicemail','call','phone','message'),
  '발신':         v('outgoing','call','send','phone'),
  '수신':         v('incoming','call','receive','phone'),
  '전화걸기':     v('calling','call','phone'),
  '전화받기':     v('incoming','call','phone','receive'),

  // ━━━ 표정/이모지 상세 ━━━
  '찡그림':       v('frown','sad','face'),
  '기진맥진':     v('weary','tired','face'),
  '실망':         v('disappointed','sad','face'),
  '안도':         v('relieved','happy','face'),
  '혼란':         v('confused','face'),
  '현기증':       v('dizzy','face'),
  '홍조':         v('flushed','face'),
  '어지러움':     v('dizzy','face'),
  '땀':           v('sweat','face','drop'),
  '구역질':       v('sick','face'),
  '낙담':         v('dissatisfied','sad','face'),
  '약간웃음':     v('slightly','smile','face'),

  // ━━━ 손동작 상세 ━━━
  '손벌림':       v('splayed','hand','finger'),
  '집기':         v('pinched','pinching','hand','finger'),
  '쥐기':         v('grip','hand','fist','finger'),
  '잡기':         v('grab','hold','hand','finger'),
  '집중손':       v('pinch','hand','finger'),
  '손흔들기':     v('waving','hand','wave'),
  '승리':         v('victory','hand','peace','finger'),
  '경례':         v('salute','hand','person'),
  '경배':         v('vulcan','hand','finger'),
  '이두박근':     v('biceps','flexed','strong'),

  // ━━━ 사람/동작 상세 ━━━
  '걷는사람':     v('walking','person','walk'),
  '뛰는사람':     v('running','person','run'),
  '앉은사람':     v('sitting','person','chair'),
  '서있는사람':   v('standing','person'),
  '무릎꿇기':     v('kneeling','person'),
  '인사':         v('bowing','person','greeting'),
  '역도':         v('lifting','weights','fitness','person'),
  '어깨올리기':   v('shrugging','person'),
  '얼굴감싸기':   v('facepalming','person'),
  '팁주기':       v('tipping','person','money'),
  '마사지':       v('massage','person','health'),
  '이발':         v('haircut','person','hair'),
  '수유':         v('feeding','person','baby'),
  '임신':         v('pregnant','person','baby'),
  '휠체어탑기':   v('motorized','wheelchair','person'),
  '지팡이':       v('cane','person','walk'),
  '터번':         v('turban','person','hat'),
  '면사포':       v('veil','person','wedding'),
  '영웅':         v('superhero','person','cape'),
  '악당':         v('supervillain','person'),
  '닌자':         v('ninja','person'),
  '요정':         v('fairy','person','magic'),
  '엘프':         v('elf','person','magic'),
  '뱀파이어':     v('vampire','person','dark'),
  '좀비':         v('zombie','person','dead'),
  '마법사':       v('mage','person','magic','wand'),
  '산타':         v('claus','person','christmas'),
  '선녀':         v('fairy','person'),

  // ━━━ 스포츠 상세 ━━━
  '핸드볼':       v('handball','sport','ball'),
  '스케이팅':     v('skating','sport','ice'),
  '스케이트보드': v('skateboarding','sport'),
  '복싱':         v('boxing','sport','fight'),
  '수중':         v('diving','swim','water','sport'),
  '스노보드':     v('snowboarder','snow','sport'),
  '볼링':         v('bowling','sport','ball'),
  '당구':         v('billiard','ball','sport'),
  '포커':         v('poker','card','game'),
  '체스기물':     v('pawn','chess','game'),
  '체스룩':       v('rook','chess','game'),
  '체스나이트':   v('knight','chess','game'),
  '마작':         v('mahjong','game'),
  '조깅':         v('running','person','sport','fitness'),
  '골프치기':     v('golfing','golf','sport'),
  '크리켓':       v('cricket','sport','ball'),
  '하키':         v('hockey','sport','ball'),

  // ━━━ 날씨 상세 ━━━
  '소나기':       v('showers','rain','cloud','weather'),
  '우박':         v('hail','rain','ice','weather'),
  '번개폭풍':     v('thunderstorms','thunder','lightning','storm'),
  '맑음':         v('sunny','sun','clear','weather'),
  '흐림':         v('cloudy','cloud','weather'),
  '부분구름':     v('partly','cloud','sun','weather'),
  '뇌우':         v('thunderstorm','storm','rain','lightning'),
  '보퍼트':       v('beaufort','wind','weather'),
  '기온':         v('temperature','thermometer','celsius','fahrenheit'),
  '섭씨':         v('celsius','temperature','thermometer'),
  '화씨':         v('fahrenheit','temperature','thermometer'),
  '이슬비':       v('drizzle','rain','cloud','weather'),
  '토네이도':     v('tornado','storm','wind','weather'),
  '허리케인':     v('hurricane','storm','wind','weather'),
  '달모양':       v('gibbous','moon','night'),
  '초승달모양':   v('waning','moon','crescent'),

  // ━━━ 의류/헤어 상세 ━━━
  '금발':         v('blonde','blond','hair'),
  '파마':         v('perm','hair','curly'),
  '스킨케어':     v('skin','care','face'),
  '코트':         v('coat','clothing','winter'),
  '스카프':       v('headscarf','scarf','clothing'),
  '머리띠':       v('band','hair','head'),
  '선글라스':     v('sunglasses','glasses','sun'),

  // ━━━ 음식/음료 상세 ━━━
  '아보카도':     v('avocado','food'),
  '팝콘':         v('popcorn','food','movie'),
  '당근':         v('carrot','food','vegetable'),
  '버섯':         v('mushroom','food','nature'),
  '바나나':       v('banana','food','fruit'),
  '체리':         v('cherries','fruit','food'),
  '감자튀김':     v('fries','food','fast'),
  '칵테일':       v('cocktail','drink','party'),
  '피처':         v('pitcher','drink','water'),
  '항아리':       v('jar','food','storage'),
  '냄비':         v('pot','food','cook','kitchen'),
  '오븐':         v('oven','cook','kitchen','food'),
  '주전자':       v('kettle','drink','kitchen'),
  '전자레인지':   v('microwave','cook','kitchen'),
  '식기세척기':   v('dishwasher','clean','kitchen'),
  '아이스크림콘': v('icecream','food','cold'),
  '맥주캔':       v('can','beer','drink'),
  '와인잔':       v('wine','glass','drink'),
  '피자조각':     v('pizza','food','slice'),
  '저울':         v('scale','weight','measure'),

  // ━━━ 가정/인테리어 ━━━
  '소파':         v('sofa','furniture','chair','home'),
  '의자':         v('chair','seat','furniture'),
  '벽난로':       v('fireplace','home','fire','warm'),
  '풍차':         v('windmill','energy','wind'),
  '창문블라인드': v('blinds','window','home'),
  '나무화분':     v('potted','plant','flower','home'),
  '캔들':         v('candle','light','fire','home'),
  '침대측면':     v('bedside','bed','sleep','home'),
  '트레드밀':     v('treadmill','fitness','run','gym'),
  '스쿠터전동':   v('scooter','electric','vehicle'),

  // ━━━ 업무/생산성 ━━━
  '계층구조':     v('hierarchy','chart','structure','tree'),
  '다이어그램':   v('diagram','chart','flow','data'),
  '플로우차트':   v('flowchart','diagram','flow','chart'),
  '간트차트':     v('gantt','chart','schedule','project'),
  '사이트맵':     v('sitemap','map','structure','web'),
  '로드맵':       v('roadmap','map','plan','chart'),
  '대시보드':     v('dashboard','chart','data','analytics'),
  '스프레드시트': v('spreadsheet','table','data','chart'),
  '할일목록':     v('checklist','task','list','todo'),
  '체크리스트':   v('checklist','task','list','check'),
  '뱃지알림':     v('badged','badge','notification','alert'),
  '스크린샷':     v('screenshot','camera','screen','capture'),
  '복사붙여넣기': v('clipboard','copy','paste','document'),
  '실행취소':     v('undo','arrow','back','history'),
  '다시실행':     v('redo','arrow','forward','history'),
  '돌아가기':     v('return','back','arrow','undo'),
  '배포':         v('deploy','deployed','server','cloud','upload'),
  '배포완료':     v('deployed','check','server','cloud'),
  '아웃박스':     v('outbox','send','mail','email'),
  '우편함':       v('mailbox','mail','email','inbox'),
  '서명':         v('signature','pen','document','sign'),
  '창고':         v('warehouse','storage','box','building'),
  '보관함':       v('tray','storage','box','archive'),

  // ━━━ 디자인/그래픽 ━━━
  '스타일러스':   v('stylus','pen','draw','edit'),
  '색상추출':     v('dropper','eyedropper','color','picker'),
  '피커':         v('picker','color','select'),
  '스포이드':     v('dropper','eyedropper','color','picker'),
  '추상':         v('abstract','art','design','creative'),
  '벡터':         v('vector','design','path','art'),
  '베지어':       v('bezier','curve','design','path'),
  '경로':         v('path','route','bezier','map'),
  '그라디언트':   v('gradient','color','design'),
  '질감':         v('texture','design','pattern'),
  '패턴':         v('pattern','design','texture'),
  '픽셀':         v('pixel','image','screen','design'),
  '뷰포트':       v('viewport','screen','view'),
  '캔버스':       v('canvas','draw','art','design'),
  '레이어관리':   v('layers','design','stack'),
  '자르기도구':   v('crop','scissors','cut','edit'),
  '클로버':       v('clover','nature','leaf','plant'),

  // ━━━ 의료/과학 상세 ━━━
  '허파':         v('lungs','medical','health','body'),
  '뇌':           v('brain','medical','health','mind'),
  '분자':         v('molecule','science','chemistry'),
  '씨앗':         v('seedling','plant','nature','grow'),
  '발육':         v('seedling','grow','plant','nature'),
  '방사능':       v('radioactive','warning','danger','nuclear'),
  '생물위험':     v('biohazard','warning','danger'),
  '소독제':       v('sanitizer','clean','medical','hand'),
  '안전모':       v('ppe','safety','helmet','medical','construction'),
  '붕대':         v('bandage','medical','aid','health'),
  '처방전':       v('prescription','medical','document','pill'),
  '영양':         v('nutrition','food','health','medical'),
  '헬멧':         v('helmet','safety','protection','construction'),

  // ━━━ 건축/인프라 ━━━
  '경기장':       v('stadium','sport','building'),
  '교회':         v('mosque','church','building','religion'),
  '궁전':         v('castle','building','monument'),
  '탑':           v('tower','building','structure'),
  '아치':         v('arch','bridge','structure'),
  '굴뚝':         v('chimney','building','smoke','fire'),
  '분수':         v('fountain','water','outdoor','garden'),
  '천장':         v('ceiling','room','home','interior'),
  '보도블록':     v('floor','tile','surface','room'),
  '창고`:':       v('warehouse','storage','building'),

  // ━━━ 교통/차량 상세 ━━━
  '트랙터':       v('tractor','vehicle','farm','agriculture'),
  '모페드':       v('moped','scooter','vehicle','motorcycle'),
  '유모차':       v('stroller','baby','person','walk'),
  '견인차':       v('tow','truck','vehicle','road'),
  '전차':         v('tram','train','transport','rail'),
  '범선':         v('sailboat','boat','ship','water'),
  '구명보트':     v('lifebuoy','boat','safety','water','rescue'),
  '셔틀':         v('shuttle','transport','bus','airplane'),
  '인력거':       v('rickshaw','vehicle','transport'),
  '출발':         v('departure','airplane','travel','flight'),
  '착륙':         v('landing','airplane','flight','travel'),
  '이륙':         v('takeoff','airplane','flight','travel'),

  // ━━━ 에너지/환경 ━━━
  '태양광':       v('solar','sun','energy','electric'),
  '전구소켓':     v('bulb','socket','electric','power'),
  '콘센트':       v('outlet','electric','plug','power'),
  '발전기':       v('generator','electric','power','energy'),
  '연료탱크':     v('tank','fuel','gas','storage'),
  '에코':         v('ecology','leaf','nature','green','recycle'),
  '재활용':       v('recycle','ecology','leaf','green'),
  '밀':           v('wheat','food','nature','plant'),
  '나무그루터기': v('tree','nature','forest','wood'),

  // ━━━ 스마트홈/IoT ━━━
  '스마트홈':     v('smart','home','wifi','network'),
  '온도조절기':   v('thermostat','temperature','home','smart'),
  '도어벨':       v('doorbell','bell','home','door'),
  '전광판':       v('signage','display','screen','ad'),
  '추적':         v('tracking','location','gps','map'),
  '센서감지':     v('sensor','detect','smart','wireless'),
  '동작감지':     v('motion','sensor','detect','camera'),

  // ━━━ 게임/엔터 ━━━
  '스팀':         v('steam','game','controller'),
  '수중바이킹':   v('rowing','water','sport','boat'),
  '롤러스케이트': v('roller','skate','sport'),
  '서커스':       v('circus','entertainment','clown'),
  '마술':         v('magic','wand','star','sparkle'),
  '불꽃놀이':     v('firework','fire','star','celebration'),
  '페리':         v('ferris','wheel','fun','park'),
  '놀이공원':     v('park','fun','entertainment','ferris'),

  // ━━━ 숫자/기호 보충 ━━━
  '퍼센트기호':   v('percent','number','math'),
  '무한대':       v('infinity','loop','math','symbol'),
  '앰퍼샌드':     v('ampersand','symbol','text'),
  '소수점':       v('decimal','number','dot','math'),
  '이진수':       v('binary','number','code','data'),
  '캐릭터':       v('character','letter','text','font'),
  '달러표시':     v('dollar','money','currency','finance'),
  '루블':         v('ruble','money','currency','russia'),
  '인도루피':     v('rupee','money','currency','india'),
  '위안':         v('yuan','money','currency','china'),
  '위':           v('won','money','currency','korea'),

  // ━━━ 방향/정렬 보충 ━━━
  '오름차순':     v('ascending','sort','order','list'),
  '내림차순':     v('descending','sort','order','list'),
  '시계반대방향': v('counterclockwise','rotate','arrow'),
  '수평정렬':     v('horizontal','align','layout'),
  '수직정렬':     v('vertical','align','layout'),
  '왼쪽방향':     v('leftwards','left','arrow'),
  '오른쪽방향':   v('rightwards','right','arrow'),
  '대각선':       v('diagonal','angle','line'),
  '구부러짐':     v('bend','curve','path'),
  '구불구불':     v('curving','curve','wave'),
  '분기점':       v('fork','branch','split','path'),

  // ━━━ 상태/모드 보충 ━━━
  '꽉참':         v('full','complete','max','capacity'),
  '반쯤':         v('half','partial','middle'),
  '분기':         v('split','fork','branch','divide'),
  '열린상태':     v('opened','open','door','unlock'),
  '닫힌상태':     v('closed','close','door','lock'),
  '잠금해제상태': v('unlocked','lock','open','security'),
  '뮤트됨':       v('muted','volume','sound','off'),
  '방해금지':     v('disturb','mute','notification','off'),
  '오프라인상태': v('offline','disconnect','signal','network'),
  '비행기모드':   v('airplane','mode','flight','off','wifi'),
  '절전모드':     v('sleep','power','battery','moon'),
  '알림음소거':   v('muted','notification','bell','off'),
  '스누즈':       v('snooze','alarm','sleep','clock'),

  // ━━━ 텍스트/문서 보충 ━━━
  '글머리기호':   v('bullet','list','text'),
  '번호목록':     v('numbered','list','number','text'),
  '단락들여쓰기': v('indent','paragraph','text'),
  '윗첨자':       v('superscript','text','math'),
  '아랫첨자':     v('subscript','text','math'),
  '캡션자막':     v('caption','subtitles','text','video'),
  '자막':         v('subtitles','caption','text','video'),
  '인용부호':     v('quote','text','symbol'),
  '북마크추가':   v('bookmark','save','mark','favorite'),
  '인용글':       v('quote','text','bubble','chat'),
  '초안':         v('draft','document','pencil','edit'),
  '임시저장':     v('draft','save','document','clock'),

  // ━━━ 레이아웃/UI 보충 ━━━
  '슬라이더들':   v('sliders','slider','settings','filter'),
  '드로어':       v('drawer','menu','sidebar','panel'),
  '스피너':       v('spinner','loading','circle','sync'),
  '프로그레스바': v('progress','bar','loading','sync'),
  '배지달린':     v('badged','badge','notification'),
  '팝오버':       v('tooltip','popup','info','help'),
  '스크롤바':     v('scroll','bar','drag'),
  '캐러셀':       v('carousel','slide','image','gallery'),
  '탭바':         v('tabs','tab','navigation','bar'),
  '케밥메뉴':     v('kebab','menu','dots','more'),
  '햄버거버튼':   v('hamburger','menu','bar','navigation'),
  '드롭다운':     v('dropdown','select','arrow','menu'),
  '다이얼패드':   v('dialpad','phone','number','call'),
  '키패드':       v('keypad','number','phone','input'),
  '검색창':       v('search','input','magnifying','find'),
  '전체보기':     v('expand','full','view','maximize'),
  '분할화면':     v('splitscreen','split','screen','view'),
  '창전환':       v('window','switch','tab','view'),
  '앱스위처':     v('apps','grid','window','switch'),

  // ━━━ 소셜/커뮤니티 보충 ━━━
  '팔로워':       v('people','person','social','follow'),
  '맞팔':         v('people','social','network','follow'),
  '댓글들':       v('comments','comment','chat','bubble'),
  '버블들':       v('bubbles','bubble','chat','comment'),
  '해시태그':     v('hashtag','hash','tag','social'),
  '멘션':         v('mention','at','social','message'),
  '스레드':       v('threads','social','message','comment'),
  '프로필사진':   v('avatar','profile','person','user'),
  '커버사진':     v('image','photo','background','cover'),
  '스토리':       v('story','stories','social','circle'),

  // ━━━ 보안/개인정보 보충 ━━━
  '익명':         v('incognito','mask','anonymous','person'),
  '잠금화면':     v('lock','screen','security','phone'),
  '보호됨':       v('protection','shield','security','check'),
  '암호화':       v('encryption','lock','security','key'),
  '방화벽':       v('firewall','shield','security','network'),
  '백도어':       v('backdoor','security','warning','bug'),
  '취약점':       v('vulnerability','security','bug','warning'),
  '추적방지':     v('tracking','privacy','shield','incognito'),

  // ━━━ 금융/결제 보충 ━━━
  'QR결제':       v('qr','pay','scan','barcode'),
  'NFC결제':      v('nfc','pay','wireless','tap'),
  '비접촉결제':   v('contactless','pay','nfc','wireless'),
  '영수증출력':   v('receipt','print','document','pay'),
  '저금통':       v('piggy','save','money','coin'),
  '안전금고':     v('vault','safe','security','money'),
  '은행이체':     v('bank','transfer','money','send'),
  '잔액':         v('balance','money','wallet','account'),
  '예금':         v('savings','bank','money','save'),
  '신용점수':     v('credit','score','finance','chart'),
  '지폐':         v('banknote','money','cash','bill'),

  // ━━━ 교육/학습 보충 ━━━
  '강의':         v('education','study','book','person','video'),
  '온라인강의':   v('education','video','laptop','study','online'),
  '퀴즈':         v('quiz','question','education','check'),
  '수학':         v('math','calculator','number','education'),
  '화학실험':     v('chemistry','flask','beaker','lab'),
  '현미경관찰':   v('microscope','science','lab','search'),
  '지구과학':     v('earth','science','globe','nature'),
  '미술':         v('art','draw','paint','brush','creative'),
  '음악수업':     v('music','education','instrument','note'),
  '체육':         v('sport','fitness','education','run'),
  '도서실':       v('library','book','education','shelf'),

  // ━━━ 여행/관광 ━━━
  '체크인':       v('checkin','hotel','airplane','location'),
  '체크아웃':     v('checkout','hotel','door','location'),
  '예약':         v('booking','calendar','reserve','ticket'),
  '여권':         v('passport','document','travel','airplane'),
  '비자':         v('visa','document','travel','passport'),
  '지도찾기':     v('map','navigation','location','search'),
  '관광':         v('travel','camera','map','landmark'),
  '명소':         v('landmark','building','map','star'),
  '호스텔':       v('hotel','bed','travel','person'),
  '리조트':       v('hotel','beach','pool','travel'),
  '글램핑':       v('tent','star','camping','nature'),
  '트레킹':       v('hiking','mountain','walk','nature'),
  '배낭여행':     v('backpack','travel','person','walk'),
  '렌터카':       v('car','rental','travel','key'),

  // ━━━ 미디어/콘텐츠 보충 ━━━
  '썸네일':       v('thumbnail','image','photo','preview'),
  '라이브방송':   v('live','broadcast','video','stream'),
  '편집':         v('edit','cut','video','scissor','film'),
  '자막추가':     v('subtitles','caption','text','video'),
  '음량높이기':   v('volume','speaker','sound','high'),
  '음량낮추기':   v('volume','speaker','sound','low'),
  '배속재생':     v('fast','play','speed','video'),
  '구간반복':     v('loop','repeat','play','music'),
  '크로스페이드': v('transition','fade','slide','effect'),
  '씬전환':       v('transition','effect','slide','video'),
  '필터적용':     v('filter','effect','image','photo'),
  '비네팅':       v('vignette','image','effect','photo'),
  '렌즈플레어':   v('lens','light','photo','effect'),
  '노이즈':       v('noise','image','effect','static'),

  // ━━━ 수치/데이터 보충 ━━━
  '증가추세':     v('trending','increase','chart','up'),
  '감소추세':     v('trending','decrease','chart','down'),
  '평균':         v('average','chart','data','middle'),
  '합계':         v('total','sum','math','data'),
  '분포':         v('scatter','distribution','chart','data'),
  '집계':         v('aggregate','sum','data','chart'),
  '로드율':       v('usage','load','data','chart'),
  '트래픽분석':   v('analytics','traffic','data','chart'),
  '방문자':       v('person','user','analytics','visit'),

  // ━━━ 인프라/네트워크 ━━━
  '서버랙':       v('server','rack','hardware','database'),
  '데이터센터':   v('datacenter','server','cloud','building'),
  '방화벽장비':   v('firewall','network','security','server'),
  '라우팅':       v('routing','network','path','connection'),
  '로드밸런서':   v('load','balancer','server','network'),
  '컨테이너':     v('container','docker','server','cloud'),
  '배포파이프':   v('pipeline','deploy','server','cloud'),
  'CDN':          v('cdn','network','cloud','speed'),
  'DNS':          v('dns','network','domain','server'),
  '도메인':       v('domain','web','server','url'),
  '호스팅':       v('hosting','server','cloud','web'),
  '이더넷':       v('ethernet','network','cable','wired'),

  // ━━━ 색상/테마 보충 ━━━
  '밝기조절':     v('brightness','adjust','screen','sun'),
  '채도':         v('saturation','color','design','image'),
  '색조':         v('hue','color','design','image'),
  '대비':         v('contrast','image','design','brightness'),
  'HDR화면':      v('hdr','screen','display','image'),
  '노출조절':     v('exposure','photo','camera','brightness'),
  '선명도':       v('sharp','clarity','image','focus'),
  '흐림효과':     v('blur','effect','image','photo'),
  '그레이스케일': v('grayscale','color','image','bw'),
  '야간모드':     v('night','dark','moon','mode'),
  '라이트모드':   v('light','bright','sun','mode'),

  // ━━━ 성별/정체성 ━━━
  '남성기호':     v('male','gender','symbol','man'),
  '여성기호':     v('female','gender','symbol','woman'),
  '성별':         v('gender','person','symbol'),
  '트랜스젠더':   v('transgender','gender','person','symbol'),
  '성소수자':     v('rainbow','gender','pride','flag'),
  '임신부':       v('pregnant','person','baby','woman'),

  // ━━━ 접근성 보충 ━━━
  '청각장애':     v('deaf','ear','accessibility','disable'),
  '수어':         v('sign','hand','accessibility','language'),
  '시각장애':     v('blind','eye','accessibility','disable'),
  '자막지원':     v('caption','subtitles','accessibility','text'),
  '확대보기':     v('magnifying','zoom','accessibility','search'),

  // ━━━ 기타 일상어 ━━━
  '배낭':         v('backpack','bag','travel','school'),
  '지갑':         v('wallet','money','card','payment'),
  '열쇠고리':     v('keychain','key','ring','tag'),
  '나침반방향':   v('compass','direction','navigation','map'),
  '손전등':       v('flashlight','torch','light','battery'),
  '자석':         v('magnet','attract','connect'),
  '전구아이디어': v('lightbulb','idea','smart','creative'),
  '경보기':       v('alarm','warning','emergency','bell'),
  '사이렌':       v('alarm','warning','emergency','alert'),
  '버저':         v('alarm','alert','notification','bell'),
  '현수막':       v('banner','flag','sign','announcement'),
  '포스터':       v('poster','image','design','print'),
  '달력일정':     v('calendar','schedule','event','date'),
  '시간표':       v('schedule','timetable','calendar','clock'),
  '메모지':       v('sticky','note','memo','paper'),
  '포스트잇':     v('sticky','note','memo','pin'),
  '테두리':       v('border','frame','outline','edge'),
  '그림자효과':   v('shadow','effect','design'),
  '불투명도':     v('opacity','transparency','design','layer'),
  '줌인':         v('zoom','magnify','search','plus'),
  '줌아웃':       v('zoom','search','minus','shrink'),
  '회전하기':     v('rotate','spin','refresh','round'),
  '뒤집기':       v('flip','mirror','reverse','rotate'),
  '복원하기':     v('restore','undo','history','backup'),
  '내보내기':     v('export','share','send','upload'),
  '가져오기':     v('import','download','receive','file'),
  '동기화중':     v('sync','loading','refresh','update'),
  '오프라인전환': v('offline','disconnect','wifi','signal'),
  '연결끊김':     v('disconnect','offline','link','broken'),
  '새탭열기':     v('tab','external','open','link','window'),
  '현재위치':     v('location','gps','pin','map','current'),
  '경로탐색':     v('navigation','route','map','direction'),
  '즐겨찾기추가': v('bookmark','star','favorite','save','pin'),
  '공유하기':     v('share','send','export','social'),
  '링크복사':     v('link','copy','clipboard','url'),
  '인쇄하기':     v('print','paper','document','printer'),
  '스캔하기':     v('scan','camera','barcode','qr'),
  '사진촬영':     v('camera','photo','capture','shoot'),
  '동영상촬영':   v('video','camera','record','film'),
  '화면녹화':     v('screen','record','capture','video'),
  '소리녹음':     v('mic','microphone','record','audio'),
  '데이터사용량': v('usage','data','chart','analytics'),
  '배터리잔량':   v('battery','charge','low','percent'),
  '신호세기':     v('signal','wifi','cellular','strength'),
  '저장공간':     v('storage','disk','memory','cloud'),
  '파일크기':     v('file','size','data','document'),
  '폴더열기':     v('folder','open','file','directory'),
  '새폴더':       v('folder','add','new','directory'),
  '파일삭제':     v('file','delete','trash','remove'),
  '압축풀기':     v('zip','extract','folder','archive'),
  '파일이동':     v('file','move','transfer','folder'),

};

let added = 0, skipped = 0, enriched = 0;
for (const [k, arr] of Object.entries(bulk)) {
  if (arr.length === 0) { skipped++; continue; }
  if (!ko[k]) {
    ko[k] = arr;
    added++;
  } else {
    // 기존 항목에 누락된 영단어 보강
    const existing = new Set(ko[k]);
    const before = existing.size;
    arr.forEach(w => existing.add(w));
    if (existing.size > before) {
      ko[k] = [...existing];
      enriched++;
    }
  }
}

const sorted = {};
for (const key of Object.keys(ko).sort()) sorted[key] = ko[key];
fs.writeFileSync(path.join(__dirname,'..','ko_dict.json'), JSON.stringify(sorted, null, 2));
console.log(`새로 추가: ${added}개 / 보강: ${enriched}개 / 스킵(영단어없음): ${skipped}개`);
console.log(`최종 ko_dict: ${Object.keys(sorted).length}개`);
