#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const ko = JSON.parse(fs.readFileSync(path.join(__dirname,'..','ko_dict.json'),'utf8'));
const words = new Set(JSON.parse(fs.readFileSync(path.join(__dirname,'..','data','icon_words.json'),'utf8')).map(w=>w.word));
const v = (...arr) => arr.filter(w => words.has(w));

const bulk6 = {

  // ━━━ 동사+목적어 패턴 ━━━
  '메일보내기':   v('email','send','mail','compose'),
  '메일받기':     v('email','receive','inbox','mail'),
  '메일회신':     v('email','reply','respond','mail'),
  '메일전달':     v('email','forward','send','mail'),
  '전화하기':     v('phone','call','dial','contact'),
  '문자보내기':   v('sms','message','send','text'),
  '화상하기':     v('video','call','conference','camera'),
  '채팅하기':     v('chat','message','talk','bubble'),
  '미팅잡기':     v('meeting','calendar','schedule','book'),
  '약속잡기':     v('appointment','calendar','clock','schedule'),
  '일정추가':     v('calendar','add','event','schedule'),
  '알람맞추기':   v('alarm','set','clock','bell'),
  '길찾기':       v('navigation','map','route','direction'),
  '지도보기':     v('map','view','location','navigation'),
  '사진찍다':     v('camera','photo','capture','shoot'),
  '동영상찍다':   v('video','record','camera','film'),
  '음악듣기':     v('music','listen','headphone','audio'),
  '영화보기':     v('movie','watch','video','film'),
  '책읽기':       v('book','read','library'),
  '뉴스보기':     v('news','read','article','web'),
  '날씨확인':     v('weather','check','cloud','sun'),
  '지갑열기':     v('wallet','open','money','pay'),
  '카드꺼내기':   v('card','payment','credit','wallet'),
  '비밀번호입력': v('password','input','key','lock'),
  '지문찍기':     v('fingerprint','touch','biometric','security'),

  // ━━━ 상황/맥락 ━━━
  '긴급상황':     v('emergency','alert','warning','red'),
  '비상사태':     v('emergency','crisis','warning','alert'),
  '사고발생':     v('accident','warning','emergency','alert'),
  '고장났을때':   v('error','broken','repair','warning'),
  '분실했을때':   v('lost','search','warning','find'),
  '도움요청':     v('help','request','emergency','person'),
  '신고하기':     v('report','police','warning','flag'),
  '위치공유':     v('location','share','gps','person'),
  '안전귀가':     v('home','safe','person','check'),
  '미아신고':     v('child','missing','warning','person'),
  '구조요청':     v('rescue','emergency','help','sos'),
  '화재신고':     v('fire','emergency','call','warning'),
  '교통사고':     v('accident','car','warning','emergency'),

  // ━━━ 학습/업무 프로세스 ━━━
  '아이디어발상': v('idea','lightbulb','brain','creative'),
  '자료수집':     v('data','collect','search','folder'),
  '분석작업':     v('analyze','data','chart','work'),
  '초안작성':     v('draft','write','document','pencil'),
  '검토하기':     v('review','check','document','eye'),
  '수정작업':     v('edit','revise','document','pen'),
  '최종확인':     v('final','check','verify','done'),
  '제출하기':     v('submit','send','upload','done'),
  '피드백받기':   v('feedback','receive','comment','review'),
  '반영하기':     v('apply','update','change','edit'),
  '완성하다':     v('complete','done','finish','check'),
  '발행하다':     v('publish','post','send','share'),
  '배포완료':     v('deploy','done','server','check'),
  '릴리즈':       v('release','version','deploy','publish'),
  '마감준수':     v('deadline','check','calendar','done'),
  '보고완료':     v('report','done','send','check'),

  // ━━━ 기기 상태 ━━━
  '충전중':       v('charging','battery','plug','lightning'),
  '충전완료':     v('charged','battery','full','check'),
  '배터리부족':   v('battery','low','warning','red'),
  '배터리방전':   v('battery','empty','warning','dead'),
  '저장공간부족': v('storage','low','warning','full'),
  '메모리부족':   v('memory','low','warning','performance'),
  '기기과열':     v('hot','temperature','warning','device'),
  '화면깨짐':     v('screen','broken','crack','error'),
  '카메라오류':   v('camera','error','warning','fix'),
  '마이크오류':   v('microphone','error','warning','fix'),
  '스피커오류':   v('speaker','error','mute','warning'),
  '네트워크오류': v('network','error','warning','disconnect'),
  '앱충돌':       v('app','crash','error','warning'),
  '시스템오류':   v('system','error','warning','crash'),
  '업데이트필요': v('update','required','warning','new'),
  '재시작필요':   v('restart','required','warning','refresh'),

  // ━━━ 비즈니스 지표 ━━━
  '매출증가':     v('revenue','increase','chart','up','money'),
  '매출감소':     v('revenue','decrease','chart','down','money'),
  '고객증가':     v('customer','increase','person','up'),
  '고객이탈':     v('customer','churn','exit','person','down'),
  '시장점유율':   v('market','share','chart','percent'),
  '브랜드인지도': v('brand','awareness','chart','eye'),
  '클릭률':       v('click','rate','percent','analytics'),
  '노출수':       v('impression','view','eye','analytics'),
  '세션수':       v('session','count','analytics','user'),
  '활성사용자':   v('active','user','analytics','chart'),
  '신규가입자':   v('new','signup','person','up'),
  '재구매율':     v('repurchase','rate','percent','chart'),
  '만족도':       v('satisfaction','star','smile','rating'),
  '순추천지수':   v('nps','recommendation','star','chart'),
  '고객생애가치': v('lifetime','value','customer','chart'),

  // ━━━ 색깔로 찾기 ━━━
  '빨간아이콘':   v('red','fire','warning','stop','heart'),
  '파란아이콘':   v('blue','water','sky','link','info'),
  '초록아이콘':   v('green','check','leaf','success','nature'),
  '노란아이콘':   v('yellow','star','warning','sun','light'),
  '회색아이콘':   v('gray','inactive','disabled','neutral'),
  '흰아이콘':     v('white','clean','blank','light','cloud'),
  '검은아이콘':   v('black','dark','night','shadow','ink'),
  '보라아이콘':   v('purple','creative','star','gem'),
  '주황아이콘':   v('orange','fire','energy','warm','alert'),
  '분홍아이콘':   v('pink','love','heart','flower','girl'),
  '금색아이콘':   v('gold','star','trophy','premium','luxury'),
  '은색아이콘':   v('silver','medal','metal','premium'),

  // ━━━ 감각/느낌 ━━━
  '따뜻한느낌':   v('warm','sun','fire','heart','orange'),
  '차가운느낌':   v('cold','ice','blue','snow','wind'),
  '밝은느낌':     v('bright','light','sun','yellow','white'),
  '어두운느낌':   v('dark','night','black','moon','shadow'),
  '부드러운느낌': v('soft','round','smooth','gentle'),
  '강한느낌':     v('bold','strong','thick','heavy','power'),
  '활기찬느낌':   v('energy','spark','lightning','fast','fire'),
  '평화로운느낌': v('peace','calm','wave','cloud','nature'),
  '깔끔한느낌':   v('clean','minimal','white','clear','simple'),
  '화려한느낌':   v('colorful','sparkle','rainbow','star','gem'),
  '고급스러운느낌':v('premium','gold','luxury','crown','diamond'),
  '재미있는느낌': v('fun','game','star','colorful','happy'),
  '진지한느낌':   v('serious','shield','document','formal','business'),
  '귀여운느낌':   v('cute','heart','star','smile','bunny'),

  // ━━━ 접속사/관계어 검색 ━━━
  '연결과분리':   v('connect','disconnect','link','break'),
  '열기와닫기':   v('open','close','door','lock'),
  '보내기와받기': v('send','receive','upload','download'),
  '추가와삭제':   v('add','delete','plus','minus'),
  '시작과끝':     v('start','end','play','stop','flag'),
  '위와아래':     v('up','down','arrow','top','bottom'),
  '좌우':         v('left','right','arrow','direction'),
  '앞뒤':         v('forward','back','arrow','navigate'),
  '입력과출력':   v('input','output','import','export'),
  '잠금과해제':   v('lock','unlock','key','security'),

  // ━━━ 기타 자주 쓰는 표현 ━━━
  '어디서':       v('location','pin','map','where'),
  '언제':         v('calendar','clock','time','when'),
  '누가':         v('person','user','who','avatar'),
  '무엇':         v('item','object','thing','what'),
  '얼마나':       v('chart','scale','measure','how'),
  '왜':           v('question','why','info','help'),
  '어떻게':       v('guide','help','how','info','arrow'),
  '확인해':       v('check','verify','view','look'),
  '알아봐':       v('search','find','discover','info'),
  '도와줘':       v('help','support','hand','assist'),
  '알려줘':       v('info','notification','bell','alert'),
  '보여줘':       v('show','view','eye','display'),
  '열어봐':       v('open','view','unlock','explore'),
  '찾아봐':       v('search','find','magnifying','explore'),

  // ━━━ 날짜/기간 ━━━
  '오늘':         v('today','calendar','clock','now'),
  '내일':         v('tomorrow','calendar','next','arrow'),
  '어제':         v('yesterday','calendar','back','history'),
  '이번주':       v('week','calendar','current','schedule'),
  '다음주':       v('week','next','calendar','arrow'),
  '지난주':       v('week','previous','calendar','back'),
  '이번달':       v('month','calendar','current','schedule'),
  '다음달':       v('month','next','calendar','arrow'),
  '지난달':       v('month','previous','calendar','back'),
  '올해':         v('year','calendar','current','annual'),
  '내년':         v('year','next','calendar','future'),
  '작년':         v('year','previous','calendar','history'),
  '최근1주일':    v('week','recent','calendar','clock'),
  '최근1개월':    v('month','recent','calendar','clock'),
  '최근3개월':    v('quarter','recent','calendar','clock'),
  '최근1년':      v('year','recent','calendar','clock'),
  '특정날짜':     v('date','calendar','specific','pick'),
  '기간설정':     v('period','calendar','set','range'),
  '날짜범위':     v('date','range','calendar','period'),

  // ━━━ 단위/측정 ━━━
  '킬로미터':     v('km','distance','measure','road'),
  '미터':         v('meter','distance','measure','ruler'),
  '센티미터':     v('cm','measure','small','ruler'),
  '밀리미터':     v('mm','measure','tiny','ruler'),
  '킬로그램':     v('kg','weight','measure','scale'),
  '그램':         v('gram','weight','small','measure','scale'),
  '리터':         v('liter','volume','water','bottle','measure'),
  '밀리리터':     v('ml','volume','small','measure','bottle'),
  '시간(단위)':   v('hour','time','clock','measure'),
  '분(단위)':     v('minute','time','clock','measure'),
  '초(단위)':     v('second','time','clock','stopwatch'),
  '도씨':         v('celsius','temperature','thermometer'),
  '퍼센트':       v('percent','rate','number','symbol'),
  '헥토파스칼':   v('pressure','weather','measure','hpa'),

  // ━━━ 프린트/출력 상세 ━━━
  '흑백인쇄':     v('print','black','white','mono','printer'),
  '컬러인쇄':     v('print','color','colorful','printer'),
  '양면인쇄':     v('print','double','side','paper'),
  '단면인쇄':     v('print','single','side','paper'),
  'A4용지':       v('paper','a4','print','document'),
  'A3용지':       v('paper','a3','print','large'),
  '라벨인쇄':     v('label','print','tag','sticker'),
  '사진인쇄':     v('photo','print','image','paper'),
  '바코드인쇄':   v('barcode','print','label','scan'),
  '영수증인쇄':   v('receipt','print','thermal','paper'),

  // ━━━ 오피스/사무 ━━━
  '오피스365':    v('microsoft','office','cloud','document'),
  '구글워크스페이스':v('google','workspace','cloud','document'),
  '슬라이드만들기':v('presentation','slide','create','design'),
  '스프레드시트열기':v('spreadsheet','excel','open','data'),
  '문서만들기':   v('document','create','write','new'),
  '공유문서':     v('document','share','cloud','people'),
  '공동편집':     v('edit','collaborate','people','document'),
  '댓글달기':     v('comment','document','add','message'),
  '버전확인':     v('version','history','document','clock'),
  '변경이력':     v('history','change','document','clock'),
  '승인요청':     v('approval','request','document','check'),
  '서명요청':     v('signature','request','document','pen'),
  '검토요청':     v('review','request','document','person'),
  '마감알림':     v('deadline','notification','bell','calendar'),
  '우선순위':     v('priority','flag','order','important'),
  '업무위임':     v('assign','task','person','delegate'),

  // ━━━ 건강/웰빙 ━━━
  '정신건강':     v('mental','health','brain','mind','wellness'),
  '스트레스':     v('stress','brain','warning','tired','health'),
  '번아웃':       v('burnout','tired','warning','fire','stress'),
  '자기관리':     v('selfcare','health','person','heart'),
  '마음챙김':     v('mindfulness','meditation','peace','mind'),
  '웰빙':         v('wellness','health','heart','balance'),
  '긍정적사고':   v('positive','mind','smile','sun','light'),
  '감사일기':     v('gratitude','journal','heart','write'),
  '자기계발':     v('growth','person','book','star','improve'),
  '루틴':         v('routine','repeat','calendar','check'),
  '수분섭취':     v('water','drink','health','drop','bottle'),
  '영양섭취':     v('nutrition','food','health','balance'),
  '잠잘자기':     v('sleep','quality','bed','moon','health'),
  '소화건강':     v('digestion','stomach','health','food'),
  '면역력':       v('immune','health','shield','medical'),

  // ━━━ 패션/뷰티 ━━━
  '뷰티루틴':     v('beauty','routine','face','skin','care'),
  '스킨케어':     v('skincare','face','health','cream','beauty'),
  '메이크업':     v('makeup','face','beauty','color'),
  '헤어스타일':   v('hairstyle','hair','beauty','person'),
  '네일아트':     v('nail','art','beauty','color','finger'),
  '향수':         v('perfume','smell','bottle','beauty'),
  '화장품':       v('cosmetics','beauty','face','makeup'),
  '립스틱':       v('lipstick','beauty','mouth','color','red'),
  '마스카라':     v('mascara','beauty','eye','lash'),
  '아이라이너':   v('eyeliner','beauty','eye','black'),
  '파운데이션':   v('foundation','beauty','face','skin','base'),
  '선크림':       v('sunscreen','beauty','skin','sun','protect'),
  '보습크림':     v('moisturizer','skin','beauty','cream'),
  '클렌징':       v('cleanse','face','wash','beauty','clean'),
  '필링':         v('peeling','skin','beauty','exfoliate'),

  // ━━━ 반려동물 ━━━
  '반려동물':     v('pet','animal','cat','dog','heart'),
  '반려견':       v('dog','pet','animal','paw','heart'),
  '반려묘':       v('cat','pet','animal','paw','heart'),
  '동물병원':     v('vet','animal','medical','hospital','pet'),
  '펫샵':         v('pet','shop','animal','store'),
  '사료':         v('pet','food','bowl','animal'),
  '동물간식':     v('pet','treat','food','animal'),
  '목줄':         v('leash','dog','pet','walk'),
  '켄넬':         v('kennel','dog','box','pet','house'),
  '캣타워':       v('cat','tower','pet','climb'),
  '어항':         v('fish','aquarium','water','pet'),
  '새장':         v('bird','cage','pet','box'),
  '펫보험':       v('insurance','pet','animal','health','shield'),
  '동물사진':     v('animal','photo','pet','cute'),

  // ━━━ 취미/여가 상세 ━━━
  '뜨개질':       v('knit','craft','thread','hobby'),
  '자수':         v('embroidery','needle','thread','art','craft'),
  '도예':         v('pottery','art','clay','craft'),
  '목공':         v('woodwork','craft','tool','hammer'),
  '가드닝':       v('garden','plant','grow','hobby'),
  '요리취미':     v('cook','hobby','food','kitchen','creative'),
  '베이킹':       v('baking','bread','food','oven','hobby'),
  '원예':         v('garden','flower','plant','hobby'),
  '그림취미':     v('painting','art','brush','hobby','creative'),
  '사진취미':     v('photography','camera','hobby','art'),
  '악기연주':     v('instrument','music','play','hobby'),
  '보드게임':     v('boardgame','game','people','fun'),
  '카드게임':     v('cardgame','card','game','people'),
  '퍼즐조각':     v('puzzle','piece','game','brain'),
  '독서모임':     v('reading','book','group','people'),
  '영화클럽':     v('movie','club','group','film'),
  '요가모임':     v('yoga','group','people','fitness'),
  '달리기모임':   v('running','group','people','sport'),
  '등산모임':     v('hiking','group','people','mountain'),
  '자전거모임':   v('cycling','group','bike','people'),

  // ━━━ IT 트렌드어 ━━━
  '메타버스':     v('metaverse','virtual','3d','avatar','vr'),
  'NFT':          v('nft','token','digital','art','crypto'),
  '웹3.0':        v('web3','blockchain','decentralized','crypto'),
  '탈중앙화':     v('decentralized','blockchain','network','crypto'),
  'DAO':          v('dao','community','vote','blockchain'),
  '제로트러스트': v('zero','trust','security','shield','verify'),
  '엣지컴퓨팅':   v('edge','computing','server','network','fast'),
  '디지털트윈':   v('digital','twin','3d','model','mirror'),
  '스마트컨트랙트':v('smart','contract','blockchain','code','security'),
  '클라우드네이티브':v('cloud','native','container','kubernetes','server'),
  '서버리스':     v('serverless','cloud','function','code','deploy'),
  '마이크로프론트엔드':v('micro','frontend','code','component','design'),
  '데이터패브릭': v('data','fabric','network','integrate','cloud'),
  '하이퍼오토메이션':v('automation','hyper','robot','ai','workflow'),
  '시티즌개발자': v('citizen','developer','low-code','create','person'),
  '로우코드':     v('low','code','drag','create','build'),
  '노코드':       v('no','code','drag','create','tool'),
  '디지털전환':   v('digital','transform','business','cloud','tech'),
  '클라우드전환': v('cloud','migration','transfer','business','server'),

};

let added = 0, skipped = 0;
for (const [k, arr] of Object.entries(bulk6)) {
  if (arr.length === 0) { skipped++; continue; }
  if (!ko[k]) { ko[k] = arr; added++; }
}

const sorted = {};
for (const key of Object.keys(ko).sort()) sorted[key] = ko[key];
fs.writeFileSync(path.join(__dirname,'..','ko_dict.json'), JSON.stringify(sorted, null, 2));
console.log(`추가: ${added} / 스킵: ${skipped} / 최종: ${Object.keys(sorted).length}`);
