#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const ko = JSON.parse(fs.readFileSync(path.join(__dirname,'..','ko_dict.json'),'utf8'));
const words = new Set(JSON.parse(fs.readFileSync(path.join(__dirname,'..','data','icon_words.json'),'utf8')).map(w=>w.word));
const v = (...arr) => arr.filter(w => words.has(w));

const adds = {
  '눈치':         v('read','person','eye','face'),
  '센스':         v('smart','person','star','lightbulb'),
  '직관':         v('eye','brain','flash','quick'),
  '논리':         v('brain','list','structure','order'),
  '이론':         v('book','brain','document'),
  '실전':         v('practice','person','work','tool'),
  '경험치':       v('experience','star','history','work'),
  '노하우':       v('experience','brain','star','guide'),
  '역량':         v('person','star','chart','badge'),
  '강점':         v('strong','person','star','plus'),
  '자원':         v('resource','storage','database'),
  '수단':         v('tool','arrow','method','gear'),
  '접근법':       v('approach','arrow','path','method'),
  '관점':         v('eye','view','person','angle'),
  '입장':         v('person','position','arrow','view'),
  '주장':         v('megaphone','person','speech','point'),
  '의견':         v('chat','person','speech','bubble'),
  '제안':         v('lightbulb','person','arrow','idea'),
  '요청':         v('request','person','arrow','message'),
  '동의':         v('check','handshake','agree'),
  '반대':         v('cross','person','warning'),
  '중립':         v('balance','scale','neutral','center'),
  '타협':         v('handshake','balance','people','middle'),
  '합의':         v('handshake','check','people'),
  '토론':         v('chat','people','speech'),
  '설득':         v('person','speech','arrow','lightbulb'),
  '협상':         v('handshake','people','balance','talk'),
  '실행':         v('play','arrow','person','action'),
  '평가':         v('rating','star','chart','check'),
  '개선':         v('improve','up','arrow','check'),
  '최적화':       v('optimize','gear','chart','up'),
  '구조화':       v('structure','organize','chart'),
  '표준화':       v('standard','check','badge'),
  '체계화':       v('system','structure','organize','list'),
  '간소화':       v('simplify','minimize','clean','arrow'),
  '디지털화':     v('digital','transform','phone','cloud'),
  '기록하다':     v('record','note','document','pencil'),
  '추적하다':     v('track','analytics','data','arrow'),
  '관리하다':     v('manage','organize','list','gear'),
  '운영하다':     v('operate','gear','server','manage'),
  '감독하다':     v('monitor','eye','person','check'),
  '지원하다':     v('support','help','person','hand'),
  '조율하다':     v('coordinate','people','arrow','connect'),
  '통합하다':     v('integrate','merge','connect','plus'),
  '분리하다':     v('separate','split','divide','arrow'),
  '확인하다':     v('verify','check','eye','done'),
  '검증하다':     v('verify','validate','check','shield'),
  '승인하다':     v('approve','check','badge','done'),
  '거부하다':     v('reject','cancel','cross','stop'),
  '연기하다':     v('postpone','clock','calendar','later'),
  '재설정':       v('reset','refresh','return'),
  '유효화':       v('validate','check','active','shield'),
  '무효화':       v('invalidate','cross','disable','remove'),
  '배포하다':     v('deploy','upload','server','cloud'),
  '롤백하다':     v('rollback','undo','back','restore'),
  '마이그레이션': v('migrate','transfer','database','arrow'),
  '로드하다':     v('load','download','receive','cloud'),
  '캐시하다':     v('cache','save','storage','speed'),
  '트리거하다':   v('trigger','arrow','event'),
  '재시도':       v('retry','refresh','repeat','arrow'),
  '타임아웃':     v('timeout','clock','warning','stop'),
  '폴백':         v('fallback','error','alternative','arrow'),
  '페일오버':     v('failover','server','backup','switch'),
  '쿠버네티스':   v('kubernetes','container','server','cloud'),
  '도커':         v('docker','container','server','deploy'),
  '앤서블':       v('ansible','automation','server','deploy'),
  '테라폼':       v('terraform','infrastructure','cloud','code'),
  '젠킨스':       v('jenkins','ci','deploy','build'),
  'CI/CD':        v('ci','cd','deploy','automation','build'),
  '깃훅':         v('git','hook','code','trigger'),
  '코드리뷰':     v('code','review','check','person'),
  '풀리퀘스트':   v('pull','request','code','review'),
  '이슈트래커':   v('issue','track','bug','list'),
  '번 레이트':    v('burn','rate','chart','finance'),
  '런웨이':       v('runway','time','money','chart'),
  '밸류에이션':   v('valuation','money','chart','star'),
  '엑시트':       v('exit','money','startup','door'),
  'IPO':          v('ipo','stock','money','public'),
  '유니콘':       v('unicorn','startup','star','billion'),
  '데카콘':       v('star','startup','big','money'),
  '부트스트랩':   v('bootstrap','startup','self','build'),
  '엔젤투자':     v('investment','angel','startup','money'),
  '벤처캐피탈':   v('venture','capital','invest','money'),
  '액셀러레이터': v('accelerator','startup','fast','rocket'),
  '인큐베이터':   v('incubator','startup','grow','build'),
  '피벗':         v('pivot','change','direction','startup'),
  '그로스해킹':   v('growth','hack','analytics','chart'),
  '바이럴':       v('viral','share','social','fast'),
  '퍼널':         v('funnel','conversion','chart','marketing'),
  'CAC':          v('cac','cost','customer','acquisition'),
  'LTV':          v('ltv','value','customer','lifetime'),
  'ARR':          v('arr','revenue','annual','chart'),
  'MRR':          v('mrr','revenue','monthly','chart'),
  'GMV':          v('gmv','transaction','money','chart'),
  'DAU':          v('dau','user','daily','analytics'),
  'MAU':          v('mau','user','monthly','analytics'),
  '스케일업':     v('scale','up','grow','server'),
  '스케일아웃':   v('scale','out','expand','server'),
  '로드밸런싱':   v('load','balance','server','network'),
  '오토스케일링': v('auto','scaling','server','cloud'),
  '캐패시티플래닝':v('capacity','plan','server','chart'),
  '성능튜닝':     v('performance','tuning','gear','optimize'),
  '쿼리최적화':   v('query','optimize','database','speed'),
  '인덱싱':       v('index','database','search','speed'),
  '샤딩':         v('shard','database','split','server'),
  '레플리케이션': v('replication','copy','database','server'),
  '클러스터':     v('cluster','server','group','network'),
  '오케스트레이션':v('orchestration','container','manage','cloud'),
  '서킷브레이커': v('circuit','breaker','security','server'),
  '헬스체크':     v('health','check','server','monitor'),
  '그레이스풀셧다운':v('graceful','shutdown','server','stop'),
  '블루그린배포': v('deploy','blue','green','server'),
  '카나리배포':   v('canary','deploy','server','percent'),
  '피처플래그':   v('feature','flag','toggle','deploy'),
  'A/B테스트':    v('ab','test','compare','analytics'),
  '멀티변량테스트':v('multivariate','test','compare','analytics'),
  '코호트분석':   v('cohort','analysis','data','chart'),
  '퍼널분석':     v('funnel','analysis','conversion','chart'),
  '리텐션분석':   v('retention','analysis','chart','user'),
  '세그멘테이션': v('segmentation','group','data','filter'),
  '어트리뷰션':   v('attribution','analytics','data','source'),
  '리포팅':       v('reporting','chart','data','document'),
  '알림발송':     v('notification','send','bell','message'),
  '푸시알림':     v('push','notification','mobile','bell'),
  '인앱메시지':   v('in-app','message','bubble','notification'),
  '이메일캠페인': v('email','campaign','marketing','send'),
  'SMS캠페인':    v('sms','campaign','message','marketing'),
  '리타게팅':     v('retargeting','marketing','user','arrow'),
  '개인화':       v('personalization','user','settings','custom'),
  '세그먼트':     v('segment','group','data','filter'),
  '타겟팅':       v('targeting','arrow','person','marketing'),
  '노출':         v('impression','view','eye','analytics'),
  '도달':         v('reach','person','arrow','analytics'),
  '참여율':       v('engagement','rate','percent','analytics'),
};

let added = 0;
for(const [k,arr] of Object.entries(adds)) {
  if(arr.length && !ko[k]) { ko[k] = arr; added++; }
}

const sorted = {};
for(const key of Object.keys(ko).sort()) sorted[key] = ko[key];
fs.writeFileSync(path.join(__dirname,'..','ko_dict.json'), JSON.stringify(sorted,null,2));
console.log('추가:', added, '/ 최종:', Object.keys(sorted).length);
