#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const ko = JSON.parse(fs.readFileSync(path.join(__dirname,'..','ko_dict.json'),'utf8'));
const words = new Set(JSON.parse(fs.readFileSync(path.join(__dirname,'..','data','icon_words.json'),'utf8')).map(w=>w.word));
const v = (...arr) => arr.filter(w => words.has(w));

const bulk3 = {

  // ━━━ 동사형 검색어 (기존 명사에 동사형 추가) ━━━
  '검색하다':     v('search','find','magnifying'),
  '찾아보다':     v('search','find','browse','explore'),
  '열다':         v('open','door','folder','unlock'),
  '닫다':         v('close','door','exit','window'),
  '만들다':       v('create','add','new','build','design'),
  '지우다':       v('delete','erase','trash','clear'),
  '보내다':       v('send','transfer','upload','share'),
  '받다':         v('receive','download','inbox','import'),
  '저장하다':     v('save','disk','storage','bookmark'),
  '공유하다':     v('share','social','send','export'),
  '연결하다':     v('connect','link','network','join'),
  '끊다':         v('disconnect','cut','remove','exit'),
  '잠그다':       v('lock','security','password','key'),
  '풀다':         v('unlock','key','open','release'),
  '켜다':         v('power','on','toggle','switch'),
  '끄다':         v('power','off','toggle','mute'),
  '올리다':       v('upload','up','arrow','send'),
  '내리다':       v('download','down','arrow','receive'),
  '늘리다':       v('expand','zoom','increase','more'),
  '줄이다':       v('minimize','zoom','decrease','less'),
  '돌리다':       v('rotate','spin','turn','refresh'),
  '뒤집다':       v('flip','mirror','reverse'),
  '이동하다':     v('move','navigate','transfer','direction'),
  '선택하다':     v('select','check','choose','click'),
  '입력하다':     v('input','type','write','keyboard'),
  '출력하다':     v('output','print','export','display'),
  '복사하다':     v('copy','duplicate','clipboard'),
  '붙여넣다':     v('paste','clipboard','insert'),
  '잘라내다':     v('cut','scissors','crop','remove'),
  '합치다':       v('merge','combine','join','group'),
  '나누다':       v('split','divide','separate','fork'),
  '정렬하다':     v('sort','align','arrange','order'),
  '필터하다':     v('filter','sort','search','funnel'),
  '새로고침하다': v('refresh','reload','sync','update'),
  '다운로드하다': v('download','save','get','receive'),
  '업로드하다':   v('upload','send','share','cloud'),
  '설치하다':     v('install','download','add','setup'),
  '삭제하다':     v('delete','remove','trash','clear'),
  '수정하다':     v('edit','modify','fix','update'),
  '확인하다':     v('check','verify','confirm','view'),
  '취소하다':     v('cancel','close','stop','remove'),
  '신청하다':     v('apply','form','submit','send'),
  '등록하다':     v('register','add','new','form'),
  '로그인하다':   v('login','sign','enter','key'),
  '로그아웃하다': v('logout','exit','door','account'),
  '구독하다':     v('subscribe','bell','follow','notification'),
  '결제하다':     v('pay','credit','money','cart'),
  '예약하다':     v('book','reserve','calendar','ticket'),
  '주문하다':     v('order','cart','food','shopping'),
  '배달하다':     v('delivery','truck','send','package'),
  '설정하다':     v('settings','gear','configure','adjust'),
  '변경하다':     v('change','edit','modify','update'),
  '추가하다':     v('add','plus','new','insert','create'),
  '제거하다':     v('remove','delete','minus','trash'),
  '보호하다':     v('protect','shield','security','guard'),
  '차단하다':     v('block','ban','shield','stop'),
  '허용하다':     v('allow','check','open','permit'),
  '거부하다':     v('deny','block','close','cancel'),
  '알리다':       v('notify','bell','alert','notification'),
  '공지하다':     v('announce','megaphone','notification','broadcast'),
  '녹화하다':     v('record','video','camera','film'),
  '촬영하다':     v('capture','camera','photo','record'),
  '스캔하다':     v('scan','camera','barcode','qr'),
  '인쇄하다':     v('print','printer','paper','document'),
  '팩스보내다':   v('fax','send','document','paper'),
  '복원하다':     v('restore','backup','undo','history'),
  '백업하다':     v('backup','save','storage','cloud'),
  '암호화하다':   v('encrypt','lock','security','shield'),
  '복호화하다':   v('decrypt','unlock','key','security'),
  '분석하다':     v('analyze','chart','data','analytics'),
  '모니터링하다': v('monitor','watch','analytics','chart'),
  '보고하다':     v('report','document','send','data'),
  '계획하다':     v('plan','calendar','chart','document'),
  '디자인하다':   v('design','art','create','draw'),
  '개발하다':     v('develop','code','build','create'),
  '테스트하다':   v('test','check','verify','debug'),
  '배포하다':     v('deploy','server','cloud','upload'),
  '릴리즈하다':   v('release','deploy','version','publish'),

  // ━━━ 형용사형 검색어 ━━━
  '새로운':       v('new','fresh','star','add','update'),
  '오래된':       v('old','archive','history','clock'),
  '빠른':         v('fast','speed','bolt','rocket'),
  '느린':         v('slow','clock','turtle'),
  '큰':           v('large','expand','big','max'),
  '작은':         v('small','minimize','tiny','micro'),
  '높은':         v('high','up','top','mountain','tall'),
  '낮은':         v('low','down','bottom','small'),
  '강한':         v('strong','shield','power','bold'),
  '약한':         v('weak','low','battery','fragile'),
  '무거운':       v('heavy','weight','scale'),
  '가벼운':       v('light','feather','thin','small'),
  '밝은':         v('bright','sun','light','bulb'),
  '어두운':       v('dark','night','moon','shadow'),
  '따뜻한':       v('warm','sun','fire','hot','heat'),
  '차가운':       v('cold','ice','snow','freeze','wind'),
  '뜨거운':       v('hot','fire','temperature','heat'),
  '시원한':       v('cool','wind','cold','fresh'),
  '깨끗한':       v('clean','clear','wash','pure'),
  '더러운':       v('dirty','trash','warning','error'),
  '비어있는':     v('empty','blank','box','folder'),
  '가득찬':       v('full','complete','max','capacity'),
  '열린':         v('open','unlock','door','folder'),
  '닫힌':         v('closed','lock','door','window'),
  '숨겨진':       v('hidden','lock','eye','mask'),
  '공개된':       v('public','open','eye','share'),
  '무료의':       v('free','gift','open','star'),
  '유료의':       v('paid','money','lock','premium'),
  '인기있는':     v('popular','trending','star','hot','fire'),
  '최신':         v('new','update','fresh','latest'),
  '베스트':       v('best','star','top','medal','trophy'),
  '완료된':       v('done','check','complete','success'),
  '대기중인':     v('pending','clock','timer','wait'),
  '진행중인':     v('progress','loading','sync','active'),
  '실패한':       v('error','fail','warning','cross'),
  '성공한':       v('success','check','complete','star'),
  '잠긴':         v('locked','lock','security','key'),
  '열린(잠금)':   v('unlocked','open','key','security'),
  '연결된':       v('connected','link','network','wifi'),
  '끊어진':       v('disconnected','broken','offline','link'),
  '활성화된':     v('active','on','check','power'),
  '비활성화된':   v('inactive','off','disable','gray'),
  '선택된':       v('selected','check','active','highlight'),
  '선택안된':     v('unselected','empty','circle','radio'),
  '읽은':         v('read','check','message','eye'),
  '안읽은':       v('unread','notification','badge','new'),
  '중요한':       v('important','flag','star','warning','mark'),
  '긴급한':       v('urgent','warning','alarm','fast','red'),
  '삭제된':       v('deleted','trash','gone','remove'),
  '보관된':       v('archived','folder','storage','box'),
  '공유된':       v('shared','link','social','network'),
  '즐겨찾기한':   v('favorited','star','bookmark','heart'),
  '수정된':       v('modified','edit','pen','updated'),
  '승인된':       v('approved','check','verified','badge'),
  '거부된':       v('rejected','cross','cancel','ban'),

  // ━━━ 숫자/순서 한국어 ━━━
  '첫번째':       v('first','one','number','start','top'),
  '두번째':       v('second','two','number'),
  '세번째':       v('third','three','number'),
  '마지막':       v('last','end','final','flag'),
  '이전것':       v('previous','back','arrow','history'),
  '다음것':       v('next','forward','arrow'),
  '처음':         v('start','home','first','beginning'),
  '끝':           v('end','stop','finish','flag'),
  '중간':         v('middle','center','half','between'),

  // ━━━ UI/UX 상세 ━━━
  '홈화면':       v('home','screen','phone','app'),
  '잠금화면':     v('lock','screen','phone','security'),
  '앱아이콘':     v('app','icon','mobile','phone'),
  '네비게이션바': v('navigation','bar','bottom','phone'),
  '상태바':       v('status','bar','top','phone','signal'),
  '노티피케이션': v('notification','bell','alert','badge'),
  '팝업창':       v('popup','window','modal','alert'),
  '툴팁':         v('tooltip','info','help','hover'),
  '플로팅버튼':   v('floating','button','fab','add'),
  '스낵바':       v('snackbar','toast','notification','bottom'),
  '다이얼로그':   v('dialog','modal','popup','window'),
  '바텀시트':     v('sheet','bottom','drawer','panel'),
  '사이드메뉴':   v('sidebar','menu','drawer','navigation'),
  '카드컴포넌트': v('card','component','ui','design'),
  '리스트뷰':     v('list','view','scroll','items'),
  '그리드뷰':     v('grid','view','layout','image'),
  '무한스크롤':   v('infinite','scroll','load','list'),
  '당겨서새로고침':v('refresh','pull','update','loading'),
  '빈화면':       v('empty','blank','screen','box'),
  '로딩화면':     v('loading','spinner','progress','wait'),
  '에러화면':     v('error','screen','warning','sad'),
  '성공화면':     v('success','screen','check','happy'),
  '온보딩':       v('onboarding','welcome','start','person'),
  '튜토리얼화면': v('tutorial','help','guide','info'),
  '설정화면':     v('settings','screen','gear','list'),
  '프로필화면':   v('profile','person','account','screen'),
  '검색화면':     v('search','screen','input','find'),
  '결과화면':     v('result','screen','list','check'),
  '상세화면':     v('detail','screen','info','view'),
  '목록화면':     v('list','screen','items','scroll'),
  '지도화면':     v('map','screen','location','navigation'),
  '채팅화면':     v('chat','message','bubble','screen'),
  '결제화면':     v('payment','screen','money','card'),

  // ━━━ 파일 형식 ━━━
  '이미지파일':   v('image','file','photo','picture'),
  '동영상파일':   v('video','file','film','movie'),
  '음악파일':     v('audio','file','music','sound'),
  '문서파일':     v('document','file','text','word'),
  '스프레드시트파일':v('spreadsheet','file','excel','table'),
  '압축파일':     v('zip','archive','file','compress'),
  '실행파일':     v('exe','file','code','app'),
  '소스파일':     v('code','file','text','developer'),
  '폰트파일':     v('font','file','text','type'),
  '설정파일':     v('config','file','settings','gear'),
  'PDF파일':      v('pdf','file','document','page'),
  'PNG이미지':    v('png','image','file','photo'),
  'JPG이미지':    v('jpg','image','file','photo'),
  'GIF파일':      v('gif','image','animated','file'),
  'SVG파일':      v('svg','vector','design','file'),
  'MP3파일':      v('audio','mp3','music','file'),
  'MP4파일':      v('video','mp4','film','file'),
  'ZIP파일':      v('zip','archive','compress','file'),
  'CSV파일':      v('csv','data','table','file','spreadsheet'),
  'JSON파일':     v('json','data','code','file'),

  // ━━━ 네트워크/통신 상세 ━━━
  '와이파이연결': v('wifi','connect','wireless','signal'),
  '와이파이끊김': v('wifi','disconnect','off','signal'),
  '와이파이없음': v('wifi','off','signal','warning'),
  '인터넷연결':   v('internet','connect','wifi','globe'),
  '인터넷끊김':   v('internet','disconnect','offline','warning'),
  '5G':           v('signal','5g','mobile','cellular','fast'),
  '4G':           v('signal','4g','mobile','cellular'),
  'LTE':          v('lte','signal','mobile','cellular'),
  '3G':           v('signal','3g','mobile','cellular'),
  '핫스팟':       v('wifi','hotspot','mobile','share'),
  '테더링':       v('tethering','mobile','wifi','share'),
  'VPN연결':      v('vpn','security','connect','shield'),
  '방화벽설정':   v('firewall','security','settings','shield'),
  '포트포워딩':   v('network','port','server','connection'),
  '대역폭':       v('bandwidth','network','speed','data'),
  '핑':           v('ping','network','speed','check'),
  '지연시간':     v('latency','network','clock','speed'),

  // ━━━ 보안 상세 ━━━
  '2단계인증':    v('security','lock','phone','verify','key'),
  '생체인증':     v('fingerprint','face','biometric','security'),
  'PIN번호':      v('pin','number','security','lock'),
  '패턴잠금':     v('pattern','lock','security','draw'),
  '얼굴인식':     v('face','recognition','security','camera'),
  '지문인식':     v('fingerprint','biometric','security'),
  '개인정보보호': v('privacy','shield','lock','person'),
  '데이터보안':   v('security','data','shield','lock'),
  '계정보안':     v('account','security','lock','shield'),
  '보안업데이트': v('security','update','shield','check'),
  '피싱방지':     v('phishing','security','warning','shield'),
  '스팸필터':     v('spam','filter','mail','shield'),
  '악성코드':     v('malware','virus','security','warning','bug'),
  '랜섬웨어':     v('ransomware','lock','warning','security'),

  // ━━━ 기기/하드웨어 상세 ━━━
  '맥북':         v('laptop','mac','apple','computer'),
  '아이맥':       v('imac','desktop','apple','computer'),
  '아이폰':       v('iphone','apple','phone','mobile'),
  '아이패드':     v('ipad','tablet','apple','screen'),
  '애플워치':     v('watch','apple','smart','wearable'),
  '안드로이드폰': v('android','phone','mobile','google'),
  '스마트TV':     v('smart','tv','screen','wifi'),
  '게임콘솔':     v('console','game','controller','play'),
  '드론':         v('drone','camera','fly','aerial','photo'),
  '스마트스피커': v('speaker','smart','wifi','voice','home'),
  '키보드마우스': v('keyboard','mouse','computer','input'),
  '조이스틱컨트롤러':v('joystick','controller','game','play'),
  '그래픽카드':   v('gpu','graphic','chip','performance'),
  '메모리카드':   v('memory','card','storage','sd'),
  'SSD':          v('ssd','storage','disk','fast'),
  'HDD':          v('hdd','storage','disk','hard'),
  '외장하드':     v('external','storage','disk','usb'),
  'USB드라이브':  v('usb','storage','disk','portable'),
  '충전기':       v('charger','charging','cable','plug'),
  '배터리팩':     v('battery','pack','portable','charging'),
  '전원어댑터':   v('adapter','power','plug','cable'),
  '케이블연결':   v('cable','connect','usb','wire'),

  // ━━━ 날짜/시간 관련 ━━━
  '오전':         v('morning','sun','clock','am'),
  '오후':         v('afternoon','sun','clock','pm'),
  '주간':         v('week','calendar','schedule'),
  '월간':         v('month','calendar','schedule'),
  '연간':         v('year','calendar','schedule','annual'),
  '분기':         v('quarter','calendar','chart','month'),
  '반기':         v('half','calendar','year','schedule'),
  '데드라인':     v('deadline','calendar','warning','clock'),
  '마감날짜':     v('deadline','calendar','date','warning'),
  '시작날짜':     v('start','calendar','date','clock'),
  '종료날짜':     v('end','calendar','date','flag'),
  '반복일정':     v('repeat','calendar','loop','schedule'),
  '알람설정':     v('alarm','clock','setting','bell'),
  '타임존':       v('timezone','globe','clock','world'),
  '날짜선택':     v('calendar','date','picker','select'),

  // ━━━ 음악/오디오 상세 ━━━
  '악기':         v('music','instrument','note','piano'),
  '기타':         v('guitar','music','instrument'),
  '피아노':       v('piano','music','instrument','keyboard'),
  '드럼':         v('drum','music','instrument','beat'),
  '바이올린':     v('violin','music','instrument'),
  '플룻':         v('flute','music','instrument','wind'),
  '노래방':       v('karaoke','microphone','music','sing'),
  '악보':         v('music','note','sheet','document'),
  '박자':         v('beat','music','time','rhythm'),
  '멜로디':       v('melody','music','note','sound'),
  '화음':         v('chord','music','note','harmony'),
  '음량증가':     v('volume','up','arrow','speaker'),
  '음량감소':     v('volume','down','arrow','speaker'),
  '이퀄라이저':   v('equalizer','audio','slider','frequency'),
  '베이스':       v('bass','music','audio','low'),
  '트레블':       v('treble','music','audio','high'),
  '스테레오':     v('stereo','audio','speaker','sound'),
  '모노':         v('mono','audio','speaker','single'),
  '오디오품질':   v('quality','audio','sound','settings'),

  // ━━━ 영상/카메라 상세 ━━━
  '4K영상':       v('4k','video','quality','screen'),
  'HD영상':       v('hd','video','quality','screen'),
  '해상도':       v('resolution','screen','display','quality'),
  '프레임레이트': v('fps','video','speed','quality'),
  '비트레이트':   v('bitrate','video','quality','data'),
  '화면비율':     v('aspect','ratio','screen','display'),
  '가로모드':     v('landscape','rotation','screen'),
  '세로모드':     v('portrait','rotation','screen'),
  '카메라전환':   v('camera','flip','switch','front'),
  '플래시켜기':   v('flash','camera','light','on'),
  '플래시끄기':   v('flash','camera','off','light'),
  '셀프타이머':   v('timer','camera','self','clock'),
  '연속촬영':     v('camera','burst','multiple','fast'),
  '슬로모션':     v('slow','video','motion','speed'),
  '타임랩스':     v('timelapse','time','speed','video'),
  '라이브포커스': v('focus','camera','portrait','blur'),
  '광각':         v('wide','camera','lens','angle'),
  '망원':         v('zoom','camera','lens','far','telescope'),

  // ━━━ 스마트폰 기능 ━━━
  '화면밝기':     v('brightness','screen','adjust','sun'),
  '야간모드설정': v('night','dark','moon','mode','settings'),
  '청색광차단':   v('blue','light','screen','eye','night'),
  '눈편안모드':   v('eye','comfort','screen','light'),
  '화면잠금':     v('screen','lock','sleep','power'),
  '화면꺼짐':     v('screen','off','sleep','power'),
  '진동모드':     v('vibrate','phone','silent','notification'),
  '무음모드':     v('silent','mute','phone','notification'),
  '비행기모드':   v('airplane','mode','off','wifi'),
  '절전모드설정': v('battery','save','sleep','power','mode'),
  '핫스팟켜기':   v('hotspot','wifi','share','mobile'),
  '블루투스켜기': v('bluetooth','on','connect','wireless'),
  '위치서비스':   v('location','gps','permission','map'),
  '카메라권한':   v('camera','permission','privacy'),
  '마이크권한':   v('microphone','permission','privacy'),
  '저장소접근':   v('storage','permission','folder','file'),
  '연락처접근':   v('contact','permission','person','privacy'),
  '폰트크기':     v('font','size','text','accessibility'),
  '디스플레이설정':v('display','settings','screen','brightness'),

  // ━━━ 웹/브라우저 ━━━
  '북마크(웹)':   v('bookmark','browser','star','web'),
  '방문기록':     v('history','browser','clock','web'),
  '탭관리':       v('tab','browser','window','organize'),
  '시크릿모드':   v('incognito','browser','private','mask'),
  '확장프로그램': v('extension','browser','plugin','code'),
  '주소창':       v('url','address','browser','input'),
  '홈페이지':     v('home','web','browser','house'),
  '새탭':         v('tab','new','browser','plus'),
  '새창':         v('window','new','browser','plus'),
  '팝업차단':     v('popup','block','browser','shield'),
  '쿠키설정':     v('cookie','privacy','browser','settings'),
  '캐시삭제':     v('cache','clear','delete','browser'),
  '자동완성':     v('autocomplete','input','keyboard','list'),
  '비밀번호저장': v('password','save','key','browser'),
  '웹페이지저장': v('save','page','document','browser'),
  '소스보기':     v('source','code','view','browser'),
  '개발자도구':   v('developer','tools','code','browser'),
  '반응형디자인': v('responsive','design','screen','mobile'),

  // ━━━ 클라우드/스토리지 ━━━
  '클라우드저장': v('cloud','save','storage','upload'),
  '클라우드백업': v('cloud','backup','save','storage'),
  '클라우드동기화':v('cloud','sync','refresh','update'),
  '구글드라이브': v('drive','cloud','google','storage'),
  '원드라이브':   v('cloud','microsoft','storage','drive'),
  '아이클라우드': v('cloud','apple','storage','sync'),
  '드롭박스':     v('dropbox','cloud','storage','folder'),
  '공유폴더':     v('folder','share','cloud','people'),
  '팀드라이브':   v('drive','team','people','storage'),
  '오프라인파일': v('file','offline','storage','download'),
  '저장공간부족': v('storage','warning','full','disk'),
  '파일동기화':   v('file','sync','cloud','update'),

  // ━━━ AI/ML 상세 ━━━
  '챗봇':         v('chatbot','bot','message','ai'),
  'ChatGPT':      v('ai','chat','message','robot'),
  '자동번역':     v('translate','ai','language','auto'),
  '음성인식':     v('voice','recognition','microphone','ai'),
  '이미지인식':   v('image','recognition','ai','camera'),
  '추천알고리즘': v('recommend','ai','star','algorithm'),
  '딥러닝':       v('ai','brain','data','neural','machine'),
  '신경망':       v('neural','network','brain','ai','node'),
  '자연어처리':   v('nlp','language','text','ai','brain'),
  '컴퓨터비전':   v('vision','camera','ai','eye','recognition'),
  '예측분석':     v('prediction','analytics','chart','ai','data'),
  '데이터마이닝': v('data','mining','analytics','database'),

  // ━━━ IoT/스마트기기 ━━━
  '스마트조명':   v('smart','light','bulb','home','wifi'),
  '스마트잠금':   v('smart','lock','security','door','wifi'),
  '스마트카메라': v('smart','camera','security','wifi','home'),
  '스마트플러그': v('smart','plug','power','wifi','home'),
  '에너지관리':   v('energy','monitor','home','chart','smart'),
  '공기질':       v('air','quality','sensor','home','health'),
  '습도조절':     v('humidity','temperature','home','smart'),
  '자동화규칙':   v('automation','rule','smart','settings','home'),

  // ━━━ 금융 앱 기능 ━━━
  '계좌조회':     v('account','bank','money','view','check'),
  '송금하기':     v('transfer','money','send','bank'),
  '입금확인':     v('deposit','money','receive','check'),
  '출금하기':     v('withdraw','money','remove','bank'),
  '지출내역':     v('expense','history','money','chart'),
  '수입내역':     v('income','history','money','chart'),
  '예산설정':     v('budget','settings','money','plan'),
  '목표저축':     v('saving','goal','money','piggy','target'),
  '투자포트폴리오':v('investment','portfolio','chart','money'),
  '주식시세':     v('stock','price','chart','market','money'),
  '환전하기':     v('exchange','currency','money','transfer'),
  '영수증관리':   v('receipt','manage','document','money'),

  // ━━━ 쇼핑 앱 기능 ━━━
  '위시리스트':   v('wishlist','heart','star','shopping','save'),
  '장바구니담기': v('cart','add','shopping','bag'),
  '바로구매':     v('buy','shopping','instant','money'),
  '할인쿠폰':     v('coupon','discount','percent','shopping'),
  '포인트적립':   v('point','reward','star','shopping'),
  '배송추적':     v('delivery','tracking','map','truck'),
  '반품신청':     v('return','shopping','reverse','box'),
  '교환신청':     v('exchange','shopping','replace','box'),
  '상품리뷰':     v('review','star','shopping','comment'),
  '상품문의':     v('question','shopping','message','help'),
  '품절알림':     v('stock','notification','bell','shopping'),
  '재입고알림':   v('restock','bell','notification','shopping'),

  // ━━━ 지도/위치 기능 ━━━
  '내위치':       v('location','current','pin','gps','map'),
  '목적지':       v('destination','pin','map','flag','target'),
  '경유지':       v('waypoint','pin','map','route'),
  '길찾기시작':   v('navigation','start','map','arrow','route'),
  '도보길찾기':   v('walk','navigation','map','person','route'),
  '자동차길찾기': v('car','navigation','map','route','drive'),
  '대중교통길찾기':v('transport','navigation','bus','train','map'),
  '실시간교통':   v('traffic','real','map','road','live'),
  '주차장찾기':   v('parking','find','map','car','location'),
  '반경검색':     v('radius','search','map','location','circle'),
  '즐겨찾기장소': v('favorite','location','pin','star','map'),
  '최근검색':     v('recent','search','history','clock'),

  // ━━━ 생산성 도구 ━━━
  '마인드맵':     v('mindmap','idea','brain','diagram','node'),
  '포스트잇메모': v('sticky','note','memo','reminder'),
  '체크박스목록': v('checklist','check','list','task'),
  '프로젝트관리': v('project','manage','task','chart','board'),
  '일정관리':     v('schedule','calendar','task','manage'),
  '할일관리':     v('todo','task','list','check','manage'),
  '타이머집중':   v('timer','focus','clock','productive'),
  '포모도로':     v('timer','focus','tomato','clock'),
  '습관트래커':   v('habit','track','check','calendar','repeat'),
  '목표관리':     v('goal','target','manage','chart','check'),
  '노트동기화':   v('note','sync','cloud','update'),
  '팀채팅':       v('team','chat','message','people','group'),
  '화상회의':     v('video','meeting','conference','camera','people'),
  '화면공유':     v('screen','share','present','cast'),

  // ━━━ 커스터마이즈/테마 ━━━
  '테마변경':     v('theme','change','color','settings'),
  '폰트변경':     v('font','change','text','settings'),
  '색상변경':     v('color','change','palette','settings'),
  '레이아웃변경': v('layout','change','design','settings'),
  '언어변경':     v('language','change','settings','translate'),
  '알림설정':     v('notification','settings','bell','manage'),
  '개인정보설정': v('privacy','settings','shield','person'),
  '계정설정':     v('account','settings','person','gear'),
  '앱설정':       v('app','settings','gear','configure'),

  // ━━━ 상태/프로세스 ━━━
  '처리중':       v('processing','loading','spinner','sync'),
  '분석중':       v('analyzing','loading','chart','spinner'),
  '업로드중':     v('uploading','upload','loading','cloud'),
  '다운로드중':   v('downloading','download','loading','arrow'),
  '설치중':       v('installing','loading','spinner','progress'),
  '업데이트중':   v('updating','loading','sync','spinner'),
  '연결중':       v('connecting','loading','wifi','network'),
  '인증중':       v('verifying','loading','check','security'),
  '결제중':       v('paying','loading','money','check'),
  '전송중':       v('sending','loading','arrow','upload'),
  '저장중':       v('saving','loading','disk','check'),
  '완료됨':       v('completed','check','done','success'),
  '취소됨':       v('cancelled','cross','error','stop'),
  '만료됨':       v('expired','warning','clock','error'),
  '갱신필요':     v('renewal','warning','update','calendar'),
  '확인필요':     v('confirm','check','warning','question'),
  '승인대기':     v('pending','clock','check','warning'),

  // ━━━ 이모지/표정 상세 ━━━
  '웃는얼굴':     v('smile','happy','grin','face'),
  '슬픈얼굴':     v('sad','frown','cry','face'),
  '화난얼굴':     v('angry','mad','face','red'),
  '놀란얼굴':     v('surprised','wow','face','exclamation'),
  '생각하는얼굴': v('thinking','face','chin','hmm'),
  '눙치는얼굴':   v('wink','face','eye','smile'),
  '우는얼굴':     v('crying','sad','face','tear'),
  '식은땀얼굴':   v('nervous','sweat','face','smile'),
  '하트눈얼굴':   v('love','heart','face','eyes'),
  '돈눈얼굴':     v('money','eyes','face','greedy'),
  '잠자는얼굴':   v('sleep','zzz','face','moon'),
  '마스크얼굴':   v('mask','sick','face','medical'),
  '악당얼굴':     v('evil','villain','face','dark'),
  '천사얼굴':     v('angel','halo','face','innocent'),
  '광대얼굴':     v('clown','circus','face','funny'),
  '해골머리':     v('skull','dead','face','halloween'),
  '외계인얼굴':   v('alien','ufo','face','green'),
  '로봇얼굴':     v('robot','ai','face','metal'),

  // ━━━ 기타 잡다한 검색어 ━━━
  '그냥':         v('general','basic','common','simple'),
  '기본':         v('default','basic','settings','common'),
  '일반':         v('general','normal','standard','common'),
  '특수':         v('special','unique','star','custom'),
  '전용':         v('dedicated','custom','special','exclusive'),
  '공통':         v('common','shared','general','group'),
  '개인':         v('personal','private','person','individual'),
  '공개':         v('public','open','share','visible'),
  '비공개':       v('private','lock','hidden','person'),
  '임시':         v('temporary','draft','clock','timer'),
  '영구':         v('permanent','forever','save','lock'),
  '자동':         v('auto','automatic','robot','gear'),
  '수동':         v('manual','person','hand','guide'),
  '고급':         v('advanced','settings','pro','star'),
  '기본값':       v('default','settings','reset','basic'),
  '추천':         v('recommend','star','thumb','top'),
  '인기순':       v('popular','trending','star','sort'),
  '최신순':       v('latest','new','time','sort','clock'),
  '가격순':       v('price','sort','money','order'),
  '평점순':       v('rating','star','sort','review'),
  '거리순':       v('distance','location','sort','map'),
  '이름순':       v('name','sort','alphabet','list'),
  '크기순':       v('size','sort','scale','order'),
  '날짜순':       v('date','sort','calendar','clock'),

};

let added = 0, skipped = 0;
for (const [k, arr] of Object.entries(bulk3)) {
  if (arr.length === 0) { skipped++; continue; }
  if (!ko[k]) { ko[k] = arr; added++; }
}

const sorted = {};
for (const key of Object.keys(ko).sort()) sorted[key] = ko[key];
fs.writeFileSync(path.join(__dirname,'..','ko_dict.json'), JSON.stringify(sorted, null, 2));
console.log(`추가: ${added} / 스킵: ${skipped} / 최종: ${Object.keys(sorted).length}`);
