#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const ko = JSON.parse(fs.readFileSync(path.join(__dirname,'..','ko_dict.json'),'utf8'));
const words = new Set(JSON.parse(fs.readFileSync(path.join(__dirname,'..','data','icon_words.json'),'utf8')).map(w=>w.word));
const v = (...arr) => arr.filter(w => words.has(w));

const adds = {
  '태도':         v('person','behavior','face'),
  '습관':         v('repeat','calendar','routine','habit'),
  '역할':         v('role','badge','person','assign'),
  '기능':         v('function','gear','code','feature'),
  '특징':         v('feature','star','badge','check'),
  '장점':         v('advantage','plus','check','star'),
  '단점':         v('disadvantage','minus','warning'),
  '비교':         v('compare','chart','list','scale'),
  '선택지':       v('option','list','choice','select'),
  '대안':         v('alternative','arrow','switch','option'),
  '방법':         v('method','guide','arrow','help'),
  '과정':         v('process','flow','arrow','step'),
  '원인':         v('cause','question','arrow','why'),
  '영향':         v('impact','chart','arrow','effect'),
  '차이':         v('difference','compare','arrow','scale'),
  '공통점':       v('similarity','check','match'),
  '공백':         v('blank','empty','space','clear'),
  '생산성':       v('productivity','chart','up','check'),
  '효율':         v('efficiency','chart','gear','check'),
  '안정성':       v('stability','shield','check','balance'),
  '확장성':       v('scalability','grow','server','up'),
  '유지보수':     v('maintenance','wrench','tool','fix'),
  '절감':         v('save','money','down','percent'),
  '투명성':       v('transparency','eye','check','open'),
  '책임':         v('responsibility','person','badge','check'),
  '신뢰':         v('trust','shield','handshake','check'),
  '협력':         v('cooperation','handshake','people'),
  '경쟁':         v('competition','trophy','flag','race'),
  '전략':         v('strategy','plan','chess','map'),
  '전술':         v('tactic','arrow','plan'),
  '비전':         v('vision','eye','star','telescope'),
  '미션':         v('mission','flag','rocket','target'),
  '가치':         v('value','star','heart','diamond'),
  '원칙':         v('principle','document','rule','check'),
  '윤리':         v('ethics','scale','check','balance'),
  '규범':         v('norm','rule','document','check'),
  '기준':         v('criteria','check','list','measure'),
  '지침':         v('guideline','document','arrow','help'),
  '절차':         v('procedure','flow','step','list'),
  '플랫폼':       v('platform','server','cloud','build'),
  '솔루션':       v('solution','check','lightbulb','tool'),
  '서비스디자인': v('service','design','person','flow'),
  '시장조사':     v('market','research','chart','data'),
  '설문조사':     v('survey','form','people','check'),
  '포커스그룹':   v('focus','group','people','research'),
  '테스트환경':   v('test','environment','lab','server'),
  '베타테스트':   v('beta','test','person','check'),
  '알파테스트':   v('alpha','test','lab','check'),
  '버그리포트':   v('bug','report','document','warning'),
  '에러로그':     v('error','log','server','warning'),
  '크래시리포트': v('crash','report','warning','document'),
  '성능테스트':   v('performance','test','chart','speed'),
  '부하테스트':   v('load','test','server','performance'),
  '보안테스트':   v('security','test','shield','check'),
  '사용성테스트': v('usability','test','person','check'),
  '자동화테스트': v('automation','test','robot','check'),
  '단위테스트':   v('unit','test','code','check'),
  '통합테스트':   v('integration','test','connect','check'),
  '스모크테스트': v('smoke','test','quick','check'),
  '플래닝':       v('planning','calendar','chart','task'),
  '스프린트플래닝':v('sprint','plan','calendar','task'),
  '데일리스크럼': v('daily','scrum','people','meeting'),
  '회고':         v('retrospective','history','people','learn'),
  '백로그':       v('backlog','list','task','manage'),
  '스토리포인트': v('story','point','number','estimate'),
  '벨로시티':     v('velocity','speed','chart','sprint'),
  '번다운차트':   v('burndown','chart','sprint','data'),
  '트리거':       v('trigger','arrow','event','code'),
  '자동화규칙':   v('automation','rule','gear','robot'),
  '스케줄링':     v('scheduling','calendar','clock','task'),
  '큐잉':         v('queue','list','wait','order'),
  '알림규칙':     v('notification','rule','bell','settings'),
  '이메일규칙':   v('email','rule','filter','settings'),
  '웹훅설정':     v('webhook','settings','code','connect'),
  '브랜드가이드': v('brand','guide','document','design'),
  '스타일가이드': v('style','guide','design','document'),
  '디자인시스템': v('design','system','component','guide'),
  '컴포넌트라이브러리':v('component','library','design','code'),
  '원자디자인':   v('atomic','design','component','structure'),
  '프로토타입':   v('prototype','design','test','wireframe'),
  '와이어프레임': v('wireframe','design','sketch','layout'),
  '모크업':       v('mockup','design','screen','prototype'),
  '유저리서치':   v('user','research','person','study'),
  '휴리스틱평가': v('evaluation','check','list','ux'),
  '카드소팅':     v('card','sort','user','research'),
  '트리테스트':   v('tree','test','navigation','user'),
  '아이트래킹':   v('eye','tracking','research','user'),
  '클릭테스트':   v('click','test','user','research'),
  '퍼소나':       v('persona','user','person','research'),
  '사용자여정':   v('journey','user','flow','map'),
  '터치포인트':   v('touchpoint','user','contact','map'),
  '페인포인트':   v('pain','user','problem','warning'),
  '공감지도':     v('empathy','map','user','heart'),
  '경험지도':     v('experience','map','user','journey'),
  '서비스청사진': v('blueprint','service','map','design'),
  '가치제안':     v('value','proposition','star','chart'),
  '고객여정지도': v('journey','customer','map','flow'),
  '비즈니스모델': v('business','model','chart','structure'),
  '린캔버스':     v('lean','canvas','business','chart'),
  '비즈니스캔버스':v('business','canvas','model','chart'),
  'SWOT':         v('swot','analysis','chart','strategy'),
  'OKR':          v('okr','goal','target','check'),
  'SMART목표':    v('smart','goal','target','check'),
  '가설검증':     v('hypothesis','test','check','research'),
  '실험설계':     v('experiment','design','test','lab'),
  '대조군':       v('control','group','test','compare'),
  '실험군':       v('test','group','experiment','compare'),
  '유의미성':     v('significant','check','star','verify'),
  '상관관계':     v('correlation','chart','data','link'),
  '인과관계':     v('causation','arrow','data','connect'),
  '회귀분석':     v('regression','analysis','chart','data'),
  '분류모델':     v('classification','model','ai','data'),
  '군집화':       v('clustering','group','data','ai'),
  '이상감지':     v('anomaly','detection','warning','data'),
  '예측모델':     v('prediction','model','ai','chart'),
  '추천시스템':   v('recommendation','system','star','ai'),
  '감정분석':     v('sentiment','analysis','emotion','ai'),
  '텍스트분석':   v('text','analysis','data','ai'),
  '이미지분류':   v('image','classification','ai','camera'),
  '객체인식':     v('object','detection','ai','camera'),
  '얼굴인식':     v('face','recognition','ai','security'),
  '음성합성':     v('voice','synthesis','audio','ai'),
  '번역엔진':     v('translation','engine','language','ai'),
  '챗봇엔진':     v('chatbot','engine','ai','message'),
  '대화시스템':   v('dialog','system','ai','chat'),
  '지식그래프':   v('knowledge','graph','data','connect'),
  '온톨로지':     v('ontology','data','structure','connect'),
};

let added = 0;
for(const [k,arr] of Object.entries(adds)) {
  if(arr.length && !ko[k]) { ko[k] = arr; added++; }
}

const sorted = {};
for(const key of Object.keys(ko).sort()) sorted[key] = ko[key];
fs.writeFileSync(path.join(__dirname,'..','ko_dict.json'), JSON.stringify(sorted,null,2));
console.log('추가:', added, '/ 최종:', Object.keys(sorted).length);
