#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const ko = JSON.parse(fs.readFileSync(path.join(__dirname,'..','ko_dict.json'),'utf8'));
const words = new Set(JSON.parse(fs.readFileSync(path.join(__dirname,'..','data','icon_words.json'),'utf8')).map(w=>w.word));
const v = (...arr) => arr.filter(w => words.has(w));

const adds = {
  // 감정 추가
  '억울함':    v('sad','person','warning'),
  '부끄러움':  v('face','shy','blush'),
  '자신감':    v('person','star','bold'),
  '의심':      v('question','warning','eye'),
  '호기심':    v('question','lightbulb','eye','search'),
  '당황':      v('face','warning','exclamation'),
  '후회':      v('sad','back','history'),
  '반성':      v('person','think','sad'),
  '감사함':    v('heart','thanks','smile'),
  '배려':      v('heart','person','care'),
  '존경':      v('person','star','badge'),
  '응원':      v('flag','star','person','cheer'),
  '위로':      v('heart','person','hug'),
  '공감':      v('heart','person','equal'),
  '연민':      v('heart','sad','person'),

  // 인간관계
  '소통':      v('chat','people','connect','message'),
  '갈등':      v('warning','people','broken'),
  '화해':      v('handshake','people','heart'),
  '이해':      v('brain','check','person'),
  '오해':      v('question','warning','person'),
  '배신':      v('person','warning','broken','heart'),
  '용서':      v('heart','check','person'),
  '존중':      v('person','star','check'),
  '배움':      v('book','person','brain','study'),
  '나눔':      v('share','heart','people','gift'),

  // 인생
  '탄생':      v('baby','heart','star','new'),
  '성장':      v('person','up','chart','star'),
  '성숙':      v('person','star','crown'),
  '노화':      v('person','clock','old'),
  '노년':      v('older','person','clock'),
  '죽음':      v('skull','dead','cross'),
  '삶':        v('person','heart','world','life'),
  '인생':      v('person','road','map','life'),
  '기회':      v('door','star','arrow','open'),
  '도전':      v('flag','star','person','forward'),
  '극복':      v('person','up','star','mountain'),
  '포기':      v('stop','person','down','flag'),
  '지속':      v('loop','repeat','forward','continue'),
  '변화':      v('arrow','refresh','update','change'),
  '발전':      v('up','chart','star','grow'),
  '퇴보':      v('down','arrow','warning','back'),
  '혁신':      v('lightbulb','rocket','star','spark'),
  '전통':      v('building','history','old','classic'),
  '문화':      v('art','globe','people','building'),
  '역사':      v('history','clock','book','archive'),

  // 자연/환경 추가
  '산림':      v('tree','forest','nature','green'),
  '초원':      v('grass','nature','green','field'),
  '광야':      v('field','nature','empty','open'),
  '빙하':      v('ice','water','cold','nature'),
  '오아시스':  v('water','desert','palm','nature'),
  '절벽':      v('cliff','mountain','nature','danger'),
  '평원':      v('field','flat','nature','landscape'),
  '밀림':      v('jungle','tree','nature','tropical'),
  '습지':      v('water','plant','nature','marsh'),
  '갯벌':      v('beach','mud','nature','shore'),

  // 재해/위기
  '화재':      v('fire','emergency','warning','red'),
  '침수':      v('water','flood','warning','rain'),
  '붕괴':      v('building','warning','danger','collapse'),
  '폭발':      v('explosion','fire','warning','danger'),
  '방사능유출': v('radiation','warning','danger','nuclear'),
  '화학사고':  v('chemical','warning','danger','safety'),
  '가스누출':  v('gas','warning','danger','smell'),
  '전염병':    v('virus','medical','warning','mask'),

  // 물건/사물
  '열쇠고리':  v('keychain','key','ring'),
  '안전핀':    v('pin','safety','metal'),
  '클립(문구)':v('clip','paper','attach','metal'),
  '테이프(문구)':v('tape','stick','wrap','clear'),
  '포스트잇':  v('sticky','note','memo','square'),
  '화이트보드': v('whiteboard','write','board','presentation'),
  '칠판':      v('board','education','write','school'),
  '프린터용지': v('paper','print','document','white'),
  '봉투(문구)':v('envelope','paper','mail','send'),
  '우표':      v('stamp','mail','send','official'),
  '도장(문구)':v('stamp','official','ink','seal'),
  '사인펜':    v('marker','pen','color','write'),
  '형광펜':    v('highlighter','marker','color','bright'),
  '지우개':    v('eraser','clear','pencil','white'),
  '자(문구)':  v('ruler','measure','straight','line'),
  '컴퍼스':    v('compass','circle','draw','math'),
  '분도기':    v('angle','measure','math','circle'),
  '계산기(물건)':v('calculator','math','number','compute'),
  '스테이플러':v('staple','paper','bind','office'),
  '펀치기':    v('punch','paper','hole','office'),

  // 공간/장소 추가
  '놀이터':    v('park','child','fun','outdoor'),
  '수영장':    v('pool','swim','water','sport'),
  '체육관':    v('gym','fitness','sport','indoor'),
  '도서관방':  v('library','room','quiet','study'),
  '강의실':    v('classroom','education','school','room'),
  '실험실':    v('lab','science','test','research'),
  '연구소':    v('lab','research','science','building'),
  '물류센터':  v('warehouse','delivery','truck','storage'),
  '데이터센터':v('datacenter','server','cloud','building'),
  '발전소':    v('power','station','energy','building'),
  '정유소':    v('oil','refinery','factory','fuel'),
  '항구':      v('port','ship','ocean','transport'),
  '공항터미널':v('airport','terminal','airplane','building'),
  '기차역':    v('station','train','rail','transport'),
  '버스터미널':v('terminal','bus','transport','building'),
  '주유소':    v('gas','fuel','station','car'),
  '충전소':    v('charging','electric','station','car'),
  '세탁소':    v('laundry','clean','wash','service'),
  '미용실':    v('hair','salon','scissors','beauty'),
  '네일샵':    v('nail','beauty','color','shop'),

  // 직장생활
  '워라밸':    v('work','life','balance','scale'),
  '번아웃방지':v('burnout','prevent','health','work'),
  '업무효율':  v('work','efficiency','chart','gear'),
  '집중력':    v('focus','brain','target','eye'),
  '멀티태스킹':v('task','multiple','work','parallel'),
  '딥워크':    v('focus','deep','work','person'),
  '시간관리':  v('time','manage','clock','calendar'),
  '에너지관리':v('energy','manage','battery','level'),
  '스트레스관리':v('stress','manage','health','brain'),
  '팀빌딩':    v('team','build','people','group'),
  '멘토링':    v('mentor','person','guide','education'),
  '코칭':      v('coach','person','help','growth'),
  '피드백문화':v('feedback','culture','people','talk'),
  '성과인정':  v('performance','recognize','badge','star'),
  '보상체계':  v('reward','system','money','star'),
  '승진':      v('promotion','up','person','star'),
  '이직':      v('job','change','person','arrow'),
  '프리랜서':  v('freelance','person','laptop','free'),
  '부업':      v('side','job','work','money'),
  '파트타임':  v('part','time','work','clock'),

  // 디지털 콘텐츠
  '숏폼':      v('short','video','social','mobile'),
  '롱폼':      v('long','video','watch','document'),
  '인포그래픽':v('infographic','chart','design','data'),
  '카드뉴스':  v('card','news','social','image'),
  '웹드라마':  v('drama','web','video','watch'),
  '웹예능':    v('variety','web','video','fun'),
  '유튜브쇼츠':v('short','video','youtube','mobile'),
  '릴스':      v('reel','video','instagram','short'),
  '라이브커머스':v('live','shop','video','social'),
  '인플루언서':v('influencer','person','social','star'),
  '크리에이터':v('creator','person','content','star'),
  '구독자':    v('subscriber','person','bell','follow'),
  '팔로워수':  v('follower','count','number','social'),
  '조회수':    v('view','count','number','analytics'),
  '좋아요수':  v('like','count','heart','number'),
  '공유수':    v('share','count','number','social'),
  '저장수':    v('save','count','bookmark','number'),

  // 사진/영상 용어
  '원샷':      v('single','shot','camera','photo'),
  '버스트샷':  v('burst','photo','multiple','fast'),
  '타임랩스':  v('timelapse','speed','video','time'),
  '보케':      v('blur','background','photo','circle'),
  '노출값':    v('exposure','photo','brightness','camera'),
  '조리개':    v('aperture','camera','lens','circle'),
  '셔터스피드':v('shutter','speed','camera','time'),
  'ISO감도':   v('iso','camera','brightness','sensitivity'),
  '화이트밸런스':v('white','balance','color','camera'),
  '히스토그램':v('histogram','photo','chart','data'),
  'RAW파일':   v('raw','photo','file','quality'),

  // 음악 제작
  'DAW':       v('daw','music','software','studio'),
  'MIDI':      v('midi','music','keyboard','note'),
  '비트메이킹':v('beat','music','create','studio'),
  '믹싱':      v('mixing','audio','equalizer','studio'),
  '마스터링':  v('mastering','audio','final','studio'),
  '보컬':      v('vocal','microphone','singer','music'),
  '화음넣기':  v('harmony','music','note','voice'),
  '효과음':    v('sound','effect','audio','edit'),
  '샘플링':    v('sample','music','audio','cut'),
  '반주':      v('music','instrument','background','play'),

  // 게임 용어
  '캐릭터스탯':v('character','stat','game','chart'),
  '레이드보스':v('raid','boss','game','fight','warning'),
  '아이템드롭':v('item','drop','game','star'),
  '패시브스킬':v('passive','skill','game','ability'),
  '액티브스킬':v('active','skill','game','ability'),
  '궁극기':    v('ultimate','skill','game','power'),
  '강화석':    v('enhance','stone','game','upgrade'),
  '가챠':      v('gacha','random','game','gift'),
  '뽑기':      v('pull','random','game','star'),
  '코스튬':    v('costume','character','game','fashion'),
  '탈것':      v('mount','vehicle','game','ride'),
  '펫(게임)':  v('pet','companion','game','animal'),
  '파티모집':  v('party','recruit','group','game'),
  '시즌패스':  v('season','pass','game','ticket'),
  '배틀패스':  v('battle','pass','game','ticket'),

  // 영어 동사형 (마지막 보충)
  '클릭하다':  v('click','tap','select','touch'),
  '타이핑하다':v('type','keyboard','text','input'),
  '스크롤하다':v('scroll','down','move','list'),
  '스와이프하다':v('swipe','slide','gesture','touch'),
  '드래그하다':v('drag','move','transfer','hand'),
  '줌인하다':  v('zoom','in','magnify','expand'),
  '줌아웃하다':v('zoom','out','shrink','minimize'),
  '토글하다':  v('toggle','switch','on','off'),
  '슬라이드하다':v('slide','move','swipe','gesture'),
  '핀치하다':  v('pinch','zoom','touch','gesture'),
};

let added = 0;
for(const [k,arr] of Object.entries(adds)) {
  if(arr.length && !ko[k]) { ko[k] = arr; added++; }
}

const sorted = {};
for(const key of Object.keys(ko).sort()) sorted[key] = ko[key];
fs.writeFileSync(path.join(__dirname,'..','ko_dict.json'), JSON.stringify(sorted,null,2));
console.log('추가:', added, '/ 최종:', Object.keys(sorted).length);
