#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const ko = JSON.parse(fs.readFileSync(path.join(__dirname,'..','ko_dict.json'),'utf8'));
const words = new Set(JSON.parse(fs.readFileSync(path.join(__dirname,'..','data','icon_words.json'),'utf8')).map(w=>w.word));
const v = (...arr) => arr.filter(w => words.has(w));

const bulk4 = {

  // ━━━ 직업/역할 상세 ━━━
  '프로그래머':   v('developer','code','person','computer'),
  '웹개발자':     v('developer','web','code','person'),
  '앱개발자':     v('developer','app','mobile','code'),
  '데이터과학자': v('data','science','analytics','person','brain'),
  '디자이너':     v('designer','art','creative','person'),
  'UX디자이너':   v('ux','design','person','creative'),
  '그래픽디자이너':v('graphic','design','art','person'),
  '마케터':       v('marketing','person','chart','megaphone'),
  '기자':         v('reporter','news','person','microphone'),
  '사진작가':     v('photographer','camera','person','photo'),
  '영상제작자':   v('video','creator','person','camera','film'),
  '음악제작자':   v('music','producer','person','studio','mic'),
  '요리사':       v('chef','cook','person','food','restaurant'),
  '바리스타':     v('coffee','barista','person','cup','cafe'),
  '미용사':       v('hair','stylist','person','scissors'),
  '배우':         v('actor','person','theater','film'),
  '가수':         v('singer','music','person','microphone'),
  '댄서':         v('dancer','person','music','dance'),
  '운동선수':     v('athlete','sport','person','fitness'),
  '코치':         v('coach','sport','person','whistle'),
  '의사':         v('doctor','medical','person','hospital'),
  '치과의사':     v('dentist','tooth','medical','person'),
  '약사':         v('pharmacist','pill','medical','person'),
  '간호사':       v('nurse','medical','person','hospital'),
  '물리치료사':   v('therapist','medical','fitness','person'),
  '상담사':       v('counselor','person','chat','help'),
  '심리치료사':   v('therapist','brain','person','health'),
  '변호사':       v('lawyer','legal','person','document'),
  '회계사':       v('accountant','money','person','calculator'),
  '건축가':       v('architect','building','design','person'),
  '엔지니어':     v('engineer','tool','person','gear'),
  '전기기사':     v('electrician','electric','person','tool'),
  '배관공':       v('plumber','pipe','person','water','tool'),
  '목수':         v('carpenter','wood','person','tool','hammer'),
  '용접공':       v('welder','fire','person','tool','metal'),
  '운전기사':     v('driver','car','person','road'),
  '조종사':       v('pilot','airplane','person','cockpit'),
  '선원':         v('sailor','ship','person','ocean','boat'),
  '우주비행사':   v('astronaut','rocket','person','space'),
  '군인':         v('soldier','military','person','shield'),
  '경찰':         v('police','badge','person','shield'),
  '소방관':       v('firefighter','fire','person','emergency'),
  '구급대원':     v('paramedic','medical','person','emergency'),
  '사회복지사':   v('social','worker','person','heart','help'),
  '교사':         v('teacher','education','person','book'),
  '교수':         v('professor','education','person','university'),
  '강사':         v('instructor','education','person','presentation'),
  '코치(교육)':   v('coach','education','person','mentor'),
  '튜터':         v('tutor','education','person','book'),

  // ━━━ 건강/의료 상세2 ━━━
  '혈액검사':     v('blood','test','medical','lab','syringe'),
  '소변검사':     v('test','medical','lab','urine'),
  '체온측정':     v('temperature','thermometer','medical','check'),
  '혈압측정':     v('blood','pressure','medical','monitor'),
  '체중측정':     v('weight','scale','measure','medical'),
  '키측정':       v('height','measure','ruler','medical'),
  '심박수측정':   v('heart','rate','pulse','medical','monitor'),
  '산소포화도':   v('oxygen','medical','health','monitor'),
  '당뇨관리':     v('diabetes','blood','glucose','medical'),
  '고혈압관리':   v('blood','pressure','medical','heart'),
  '콜레스테롤관리':v('health','blood','medical','heart'),
  '골다공증':     v('bone','medical','health','density'),
  '관절염':       v('joint','pain','medical','body'),
  '알레르기':     v('allergy','medical','warning','health'),
  '천식':         v('asthma','lung','medical','health','breath'),
  '당뇨':         v('diabetes','medical','health','sugar'),
  '암':           v('cancer','medical','warning','health'),
  '우울증':       v('depression','sad','mental','health','brain'),
  '불면증':       v('insomnia','sleep','medical','night'),
  '비만':         v('obesity','weight','health','food'),
  '임신테스트':   v('pregnant','test','medical','woman'),
  '건강검진':     v('health','checkup','medical','check','body'),
  '예방접종':     v('vaccine','syringe','medical','protect'),
  '처방전발급':   v('prescription','document','medical','doctor'),
  '진단서':       v('diagnosis','document','medical','certificate'),

  // ━━━ 법률/행정 상세 ━━━
  '사업자등록':   v('business','register','document','official'),
  '법인설립':     v('company','document','official','business'),
  '상표등록':     v('trademark','register','document','badge'),
  '특허출원':     v('patent','document','idea','official'),
  '저작권등록':   v('copyright','document','creative','official'),
  '부동산등기':   v('property','document','official','home'),
  '차량등록':     v('vehicle','register','document','car'),
  '운전면허':     v('license','car','document','official'),
  '여권발급':     v('passport','document','official','travel'),
  '비자신청':     v('visa','document','travel','application'),
  '세금신고서':   v('tax','document','money','official'),
  '계약서작성':   v('contract','document','sign','pen'),
  '합의서':       v('agreement','document','sign','handshake'),
  '소송장':       v('lawsuit','document','court','official'),
  '판결문':       v('judgment','document','court','official'),
  '공증서류':     v('notary','document','official','stamp'),
  '법적대리인':   v('lawyer','person','document','official'),
  '형사사건':     v('criminal','court','police','law'),
  '민사사건':     v('civil','court','document','law'),

  // ━━━ 부동산/건설 ━━━
  '집매매':       v('house','buy','sell','key','money'),
  '집임대':       v('house','rent','key','money','person'),
  '원룸':         v('room','small','home','apartment'),
  '아파트':       v('apartment','building','home','room'),
  '빌라':         v('villa','building','home'),
  '오피스텔':     v('office','home','building'),
  '상가건물':     v('commercial','building','store','shop'),
  '평면도':       v('floor','plan','blueprint','building'),
  '인테리어설계': v('interior','design','home','blueprint'),
  '건축설계':     v('architecture','design','building','blueprint'),
  '철거':         v('demolish','building','remove','warning'),
  '리모델링':     v('renovation','home','design','building'),
  '측량':         v('survey','measure','map','ruler'),
  '시공':         v('construction','build','tool','worker'),
  '감리':         v('inspection','check','building','document'),
  '준공':         v('completion','building','check','official'),
  '등기이전':     v('transfer','document','property','official'),

  // ━━━ 농업/자연 ━━━
  '농장':         v('farm','agriculture','plant','field'),
  '논밭':         v('field','plant','agriculture','nature'),
  '씨앗뿌리기':   v('seed','plant','grow','nature'),
  '수확':         v('harvest','plant','food','agriculture'),
  '비료':         v('fertilizer','plant','grow','agriculture'),
  '농약':         v('pesticide','plant','warning','agriculture'),
  '온실':         v('greenhouse','plant','grow','home'),
  '수경재배':     v('hydroponic','water','plant','grow'),
  '유기농':       v('organic','plant','natural','leaf','food'),
  '텃밭':         v('garden','plant','home','grow'),
  '가축':         v('livestock','animal','farm','food'),
  '양봉':         v('bee','honey','farm','nature'),
  '낚시터':       v('fishing','water','fish','outdoor'),
  '등산코스':     v('hiking','mountain','trail','map'),
  '산불':         v('fire','mountain','warning','tree'),
  '홍수경보':     v('flood','warning','water','rain'),
  '산사태':       v('landslide','mountain','warning','danger'),
  '가뭄경보':     v('drought','sun','warning','water'),

  // ━━━ 에너지/환경 상세 ━━━
  '탄소발자국':   v('carbon','footprint','environment','leaf'),
  '탄소중립':     v('carbon','neutral','environment','globe'),
  '기후변화':     v('climate','change','globe','warning','temperature'),
  '녹색에너지':   v('green','energy','leaf','solar','wind'),
  '에너지절약':   v('energy','save','power','leaf','eco'),
  '물절약':       v('water','save','drop','eco','leaf'),
  '분리수거':     v('recycle','sort','trash','bin','leaf'),
  '친환경제품':   v('eco','product','leaf','green','nature'),
  '환경보호':     v('environment','protect','leaf','globe','nature'),
  '해양보호':     v('ocean','protect','fish','wave','nature'),
  '멸종위기':     v('animal','danger','warning','protection'),
  '자연재해':     v('disaster','warning','nature','emergency'),

  // ━━━ 금융/투자 상세2 ━━━
  '주식매수':     v('stock','buy','money','chart','up'),
  '주식매도':     v('stock','sell','money','chart','down'),
  '펀드투자':     v('fund','invest','money','chart'),
  '채권투자':     v('bond','invest','money','document'),
  '부동산투자':   v('property','invest','money','building'),
  '가상화폐투자': v('crypto','bitcoin','invest','money'),
  '해외투자':     v('foreign','invest','money','globe'),
  '배당금':       v('dividend','money','chart','receive'),
  '수익률':       v('profit','rate','money','chart','percent'),
  '손실률':       v('loss','rate','money','chart','percent'),
  '포트폴리오관리':v('portfolio','money','chart','manage'),
  '세금공제':     v('tax','deduct','money','document'),
  '연금':         v('pension','money','calendar','future'),
  '퇴직금':       v('retirement','money','work','future'),
  '건강보험':     v('insurance','health','medical','shield'),
  '생명보험':     v('insurance','life','medical','shield'),
  '자동차보험':   v('insurance','car','shield','document'),
  '재산세':       v('tax','property','money','document'),
  '소득세':       v('tax','income','money','document'),
  '부가가치세':   v('vat','tax','money','percent'),

  // ━━━ 교육 상세2 ━━━
  '유치원':       v('kindergarten','child','school','play'),
  '초등교육':     v('primary','school','child','education'),
  '중등교육':     v('secondary','school','student','education'),
  '고등교육':     v('higher','school','student','education'),
  '대학교육':     v('university','graduation','education','book'),
  '직업교육':     v('vocational','work','education','tool'),
  '평생교육':     v('lifelong','education','book','person'),
  '방과후수업':   v('afterschool','education','study','child'),
  '교환학생':     v('exchange','student','airplane','school'),
  '장학금지원':   v('scholarship','money','education','star'),
  '도서관이용':   v('library','book','education','read'),
  '실습수업':     v('practice','lab','education','tool'),
  '토론수업':     v('discussion','education','people','chat'),
  '프로젝트수업': v('project','education','group','work'),
  '플립러닝':     v('flipped','learning','video','education'),
  '블렌디드러닝': v('blended','learning','online','education'),
  'e러닝':        v('elearning','online','video','education','laptop'),
  '자기주도학습': v('self','study','education','book','person'),

  // ━━━ 스포츠 상세2 ━━━
  '프로스포츠':   v('professional','sport','person','ball'),
  '아마추어스포츠':v('amateur','sport','person','ball'),
  '팀스포츠':     v('team','sport','people','ball'),
  '개인스포츠':   v('individual','sport','person'),
  '실내스포츠':   v('indoor','sport','gym','person'),
  '야외스포츠':   v('outdoor','sport','nature','person'),
  '수상스포츠':   v('water','sport','swim','boat'),
  '빙상스포츠':   v('ice','sport','skate','cold'),
  '하계올림픽':   v('olympic','summer','sport','medal'),
  '동계올림픽':   v('olympic','winter','snow','medal'),
  '스포츠중계':   v('sport','broadcast','live','video'),
  '스포츠통계':   v('sport','statistics','chart','data'),
  '스포츠의류':   v('sport','clothing','wear','fitness'),
  '스포츠장비':   v('sport','equipment','tool','gear'),
  '트레이닝프로그램':v('training','program','fitness','plan'),
  '식이요법':     v('diet','food','health','nutrition'),
  '보충제':       v('supplement','pill','health','fitness'),
  '스포츠마사지': v('massage','sport','health','person'),
  '부상예방':     v('injury','prevent','medical','sport'),
  '재활운동':     v('rehabilitation','fitness','medical','person'),

  // ━━━ 여행/관광 상세2 ━━━
  '해외여권':     v('passport','travel','official','document'),
  '여행보험':     v('insurance','travel','shield','airplane'),
  '여행경비':     v('money','travel','budget','plan'),
  '여행일정표':   v('schedule','travel','calendar','map'),
  '여행가이드':   v('guide','travel','person','map'),
  '패키지여행':   v('package','travel','group','airplane'),
  '자유여행':     v('free','travel','person','map'),
  '배낭여행계획': v('backpack','travel','plan','map'),
  '렌터카예약':   v('rental','car','book','key'),
  '숙소예약':     v('hotel','book','bed','sleep'),
  '항공권예약':   v('airplane','ticket','book','flight'),
  '기차표예약':   v('train','ticket','book','rail'),
  '버스티켓':     v('bus','ticket','transport','travel'),
  '여행후기':     v('review','travel','comment','star'),
  '여행지추천':   v('recommend','destination','travel','star'),
  '관광명소':     v('landmark','tourism','map','star'),
  '현지음식':     v('food','local','restaurant','travel'),
  '현지교통':     v('transport','local','map','travel'),
  '환전소':       v('exchange','money','currency','location'),
  '여행준비물':   v('checklist','travel','bag','prepare'),

  // ━━━ 문화/예술 ━━━
  '미술작품':     v('art','painting','gallery','museum'),
  '조각품':       v('sculpture','art','3d','museum'),
  '사진작품':     v('photo','art','gallery','museum'),
  '디지털아트':   v('digital','art','design','creative'),
  '일러스트':     v('illustration','art','draw','design'),
  '캐릭터디자인': v('character','design','art','person'),
  '로고디자인':   v('logo','design','brand','creative'),
  '포스터디자인': v('poster','design','print','creative'),
  '패키지디자인': v('package','design','product','creative'),
  '영화':         v('movie','film','cinema','screen'),
  '드라마':       v('drama','video','screen','story'),
  '애니메이션':   v('animation','cartoon','film','art'),
  '웹툰(만화)':   v('webtoon','cartoon','art','mobile'),
  '소설':         v('novel','book','write','story'),
  '시':           v('poem','write','book','art'),
  '음악공연':     v('concert','music','person','stage'),
  '연극':         v('theater','person','stage','drama'),
  '오페라':       v('opera','music','stage','person'),
  '발레':         v('ballet','dance','person','art'),
  '뮤지컬':       v('musical','dance','music','stage','person'),

  // ━━━ 사회/정치 ━━━
  '투표하기':     v('vote','check','person','election'),
  '선거':         v('election','vote','flag','person'),
  '정부':         v('government','building','official','flag'),
  '국회':         v('congress','building','law','official'),
  '시청':         v('city','hall','building','official'),
  '구청':         v('district','office','building','official'),
  '공공기관':     v('public','institution','building','official'),
  '사회운동':     v('social','movement','people','flag'),
  '인권':         v('human','rights','person','shield','flag'),
  '평화':         v('peace','dove','flag','world','white'),
  '전쟁':         v('war','conflict','sword','shield','flag'),
  '외교':         v('diplomacy','handshake','flag','globe'),
  '국제관계':     v('international','globe','flag','handshake'),
  '경제정책':     v('economy','policy','money','chart','official'),
  '사회정책':     v('social','policy','people','document'),

  // ━━━ 과학/기술 상세2 ━━━
  '천문학':       v('astronomy','star','telescope','moon','planet'),
  '물리학':       v('physics','atom','energy','science'),
  '화학':         v('chemistry','flask','beaker','lab','science'),
  '생물학':       v('biology','leaf','cell','science','dna'),
  '지질학':       v('geology','mountain','earth','rock','science'),
  '기상학':       v('meteorology','weather','cloud','science'),
  '해양학':       v('oceanography','ocean','wave','fish','science'),
  '생태학':       v('ecology','nature','leaf','animal','science'),
  '유전공학':     v('genetics','dna','science','lab','code'),
  '나노기술':     v('nano','technology','small','chip','science'),
  '로봇공학':     v('robotics','robot','gear','science','code'),
  '우주과학':     v('space','rocket','star','science','satellite'),
  '핵물리학':     v('nuclear','atom','energy','science','warning'),
  '광학':         v('optics','light','lens','science','wave'),
  '음향학':       v('acoustics','sound','wave','science','audio'),
  '재료공학':     v('material','engineering','metal','science'),
  '항공공학':     v('aerospace','airplane','engineering','science'),
  '전자공학':     v('electronics','chip','circuit','science','code'),
  '통신공학':     v('telecommunications','signal','network','science'),
  '바이오기술':   v('biotech','science','lab','dna','cell'),

  // ━━━ 쇼핑/이커머스 상세2 ━━━
  '특가상품':     v('deal','discount','price','tag','hot'),
  '한정판매':     v('limited','sale','timer','clock','exclusive'),
  '묶음상품':     v('bundle','package','box','deal','group'),
  '사은품':       v('free','gift','present','box','shopping'),
  '적립금':       v('point','save','money','reward','star'),
  '멤버십할인':   v('membership','discount','card','percent'),
  '카드결제':     v('card','credit','payment','money'),
  '무통장입금':   v('bank','transfer','money','deposit'),
  '간편결제':     v('quick','payment','phone','money','nfc'),
  '분할납부':     v('installment','payment','money','calendar'),
  '후불결제':     v('deferred','payment','money','later'),
  '구독모델':     v('subscription','monthly','money','calendar'),
  '프리미엄서비스':v('premium','service','star','money','crown'),
  '무료배송':     v('free','delivery','truck','shipping'),
  '당일배송':     v('same','day','delivery','fast','truck'),
  '익일배송':     v('next','day','delivery','truck','fast'),
  '해외배송':     v('international','delivery','airplane','truck'),
  '배송조회':     v('delivery','tracking','location','truck'),
  '교환반품':     v('exchange','return','reverse','box'),
  '고객센터':     v('support','customer','help','call','person'),

  // ━━━ 통신/미디어 상세2 ━━━
  '문자메시지':   v('sms','message','text','phone','bubble'),
  'MMS':          v('mms','message','image','phone'),
  '이모티콘전송': v('emoji','message','sticker','send'),
  '음성통화':     v('voice','call','phone','microphone'),
  '영상통화':     v('video','call','camera','phone'),
  '그룹통화':     v('group','call','people','phone'),
  '회의통화':     v('conference','call','people','phone'),
  '콜렉트콜':     v('collect','call','phone','reverse'),
  '국제전화':     v('international','call','phone','globe'),
  '로밍':         v('roaming','phone','globe','signal'),
  '인터넷전화':   v('voip','phone','internet','call'),
  '스팸전화':     v('spam','call','phone','warning'),
  '수신거부':     v('block','call','phone','ban'),
  '녹취':         v('record','call','phone','audio'),
  '자동응답':     v('auto','answer','phone','message'),
  '대기중통화':   v('hold','call','pause','phone'),
  '착신전환':     v('forward','call','phone','arrow'),

  // ━━━ 보안/인증 상세2 ━━━
  '아이디찾기':   v('find','id','account','email','person'),
  '비밀번호찾기': v('find','password','email','reset','key'),
  '회원가입':     v('signup','register','person','form','add'),
  '계정삭제':     v('delete','account','person','remove'),
  '계정탈퇴':     v('withdraw','account','person','exit'),
  '활동내역':     v('activity','history','log','person'),
  '접속기록':     v('login','history','log','security','clock'),
  '기기관리':     v('device','manage','security','list'),
  '세션관리':     v('session','security','manage','list'),
  '접근권한':     v('permission','access','security','shield'),
  '관리자권한':   v('admin','permission','shield','person'),
  '사용자권한':   v('user','permission','person','shield'),
  '역할할당':     v('role','assign','person','badge','security'),
  '감사로그':     v('audit','log','security','document','check'),
  '보안알림':     v('security','notification','bell','shield'),

  // ━━━ 데이터/분석 상세2 ━━━
  '데이터수집':   v('data','collect','database','chart'),
  '데이터정제':   v('data','clean','filter','database'),
  '데이터변환':   v('data','transform','convert','database'),
  '데이터시각화': v('data','visualization','chart','graph'),
  '실시간데이터': v('realtime','data','live','chart'),
  '배치처리':     v('batch','process','data','server'),
  '스트림처리':   v('stream','process','data','real'),
  '데이터파이프라인':v('pipeline','data','flow','server'),
  '보고서생성':   v('report','generate','document','chart'),
  '대시보드구성': v('dashboard','configure','chart','layout'),
  'KPI':          v('kpi','metric','chart','goal','measure'),
  'ROI':          v('roi','return','money','chart','measure'),
  '전환율':       v('conversion','rate','percent','chart'),
  '이탈률':       v('bounce','rate','exit','chart','percent'),
  '체류시간':     v('time','session','clock','analytics'),
  '사용자행동':   v('user','behavior','analytics','track','person'),

  // ━━━ 게임 상세2 ━━━
  '게임서버':     v('server','game','network','online'),
  '게임업데이트': v('update','game','download','version'),
  '패치노트':     v('patch','note','game','update','document'),
  '게임내구매':   v('purchase','game','money','in-app'),
  '게임화폐':     v('coin','currency','game','gold'),
  '게임랭킹':     v('ranking','leaderboard','game','trophy','star'),
  '매치메이킹':   v('match','game','people','search'),
  '캐릭터생성':   v('character','create','person','game'),
  '캐릭터커스텀': v('character','customize','design','game'),
  '스킬트리':     v('skill','tree','game','upgrade'),
  '장비강화':     v('equipment','upgrade','star','game'),
  '길드가입':     v('guild','join','group','game'),
  '친구추가(게임)':v('friend','add','game','person'),
  '도전과제':     v('achievement','challenge','badge','game','star'),
  '일일퀘스트':   v('daily','quest','task','game','calendar'),
  '보상받기':     v('reward','receive','gift','game','star'),
  '게임설정':     v('settings','game','gear','configure'),
  '그래픽설정':   v('graphics','settings','game','display'),
  '소리설정(게임)':v('sound','settings','game','volume'),

  // ━━━ 기타 관용구/숙어 ━━━
  '한눈에':       v('overview','quick','glance','eye','view'),
  '세부사항':     v('detail','info','list','view'),
  '전체목록':     v('list','all','view','complete'),
  '자주묻는질문': v('faq','question','help','list','info'),
  '도움말센터':   v('help','center','support','question','info'),
  '시작하기':     v('start','begin','play','arrow','go'),
  '둘러보기':     v('tour','explore','view','eye','search'),
  '더보기':       v('more','dots','expand','arrow','list'),
  '접기':         v('collapse','fold','minimize','arrow','up'),
  '펼치기':       v('expand','unfold','maximize','arrow','down'),
  '위로가기':     v('scroll','top','arrow','up','back'),
  '아래로가기':   v('scroll','bottom','arrow','down'),
  '새탭에서열기': v('external','link','open','tab','new'),
  '인쇄미리보기': v('print','preview','document','eye','view'),
  '전송완료':     v('send','complete','check','success'),
  '결제완료':     v('payment','complete','check','success'),
  '등록완료':     v('register','complete','check','success'),
  '가입완료':     v('signup','complete','check','success'),
  '업로드완료':   v('upload','complete','check','success'),
  '다운로드완료': v('download','complete','check','success'),
  '설치완료':     v('install','complete','check','success'),
  '삭제완료':     v('delete','complete','check','done'),
  '저장완료':     v('save','complete','check','success'),
  '수정완료':     v('edit','complete','check','success'),
  '확인완료':     v('confirm','complete','check','success'),

  // ━━━ 한자어/고급어 ━━━
  '접속':         v('connect','login','access','enter'),
  '연동':         v('integration','connect','sync','link'),
  '매핑':         v('mapping','link','connect','data'),
  '파싱':         v('parse','code','data','process'),
  '렌더링':       v('render','display','screen','code'),
  '캐싱':         v('cache','storage','speed','server'),
  '로깅':         v('log','record','server','code'),
  '트래킹':       v('tracking','analytics','data','location'),
  '스케일링':     v('scale','resize','server','grow'),
  '클러스터링':   v('cluster','server','group','network'),
  '마이그레이션': v('migration','transfer','database','server'),
  '페이지네이션': v('pagination','page','list','navigate'),
  '필터링':       v('filter','sort','search','data'),
  '정규화':       v('normalize','data','format','database'),
  '직렬화':       v('serialize','data','convert','code'),
  '역직렬화':     v('deserialize','data','convert','code'),
  '암호화키':     v('encryption','key','security','lock'),
  '해시함수':     v('hash','security','code','data'),
  '토큰발급':     v('token','issue','security','key'),

};

let added = 0, skipped = 0;
for (const [k, arr] of Object.entries(bulk4)) {
  if (arr.length === 0) { skipped++; continue; }
  if (!ko[k]) { ko[k] = arr; added++; }
}

const sorted = {};
for (const key of Object.keys(ko).sort()) sorted[key] = ko[key];
fs.writeFileSync(path.join(__dirname,'..','ko_dict.json'), JSON.stringify(sorted, null, 2));
console.log(`추가: ${added} / 스킵: ${skipped} / 최종: ${Object.keys(sorted).length}`);
