#!/usr/bin/env node
// 2차 대량 확장
const fs = require('fs');
const path = require('path');

const ko = JSON.parse(fs.readFileSync(path.join(__dirname,'..','ko_dict.json'),'utf8'));
const words = new Set(JSON.parse(fs.readFileSync(path.join(__dirname,'..','data','icon_words.json'),'utf8')).map(w=>w.word));
const v = (...arr) => arr.filter(w => words.has(w));

// 기존 한국어 키에 동의어/변형 대거 추가 전략
const bulk2 = {

  // ━━━ 기존 항목 동의어 확장 ━━━
  // 검색
  '찾기':         v('search','find','magnifying','zoom','filter'),
  '탐색':         v('search','explore','navigation','browse','find'),
  '조회':         v('search','find','view','data','query'),
  '필터링':       v('filter','funnel','sort','search'),
  '정렬':         v('sort','align','order','list','filter'),

  // 저장/파일
  '저장하기':     v('save','floppy','disk','document','storage'),
  '내려받기':     v('download','arrow','save','file'),
  '올리기':       v('upload','arrow','send','file'),
  '첨부하기':     v('attachment','clip','file','send','paperclip'),
  '압축':         v('zip','archive','folder','compress'),
  '풀기':         v('unzip','archive','folder','extract'),
  '동기화':       v('sync','refresh','update','cloud'),
  '백업하기':     v('backup','save','storage','cloud'),

  // 편집
  '편집하기':     v('edit','pen','pencil','write','modify'),
  '수정하기':     v('edit','fix','pen','pencil','write'),
  '삭제하기':     v('delete','trash','remove','clear','bin'),
  '추가하기':     v('add','plus','create','new','insert'),
  '복사하기':     v('copy','duplicate','clipboard','paste'),
  '붙이기':       v('paste','clipboard','copy','insert'),
  '잘라내기':     v('cut','scissors','crop','edit'),
  '되돌리기':     v('undo','back','history','arrow'),
  '다시하기':     v('redo','forward','history','arrow'),
  '초기화':       v('reset','clear','refresh','restore'),
  '지우기':       v('clear','erase','delete','clean'),
  '합치기':       v('merge','combine','join','link'),
  '나누기':       v('split','divide','separate','fork'),
  '묶기':         v('group','folder','combine','link'),
  '정렬하기':     v('sort','align','order','arrange'),
  '이동하기':     v('move','drag','transfer','navigate'),
  '크기조정':     v('resize','scale','zoom','adjust'),
  '회전시키기':   v('rotate','spin','turn','refresh'),
  '뒤집기':       v('flip','mirror','reverse','turn'),

  // 보기
  '보기':         v('view','show','display','eye','visible'),
  '숨기기':       v('hide','invisible','eye','off','mask'),
  '미리보기':     v('preview','view','eye','thumbnail','image'),
  '확대하기':     v('zoom','expand','magnify','large'),
  '축소하기':     v('zoom','minimize','shrink','small'),
  '전체보기':     v('fullscreen','expand','maximize','view'),
  '창닫기':       v('close','window','exit','door'),
  '새창열기':     v('window','open','tab','external'),

  // 공유/연결
  '공유하기':     v('share','send','social','export','network'),
  '링크걸기':     v('link','connect','url','web','attach'),
  '연결하기':     v('connect','link','network','bluetooth','wifi'),
  '끊기':         v('disconnect','cut','remove','link','network'),
  '전송하기':     v('send','transfer','upload','share','arrow'),
  '받기':         v('receive','download','inbox','mail','arrow'),

  // 알림/상태
  '알림받기':     v('notification','bell','alert','message'),
  '알림끄기':     v('mute','notification','bell','off','disable'),
  '경고표시':     v('warning','alert','exclamation','caution'),
  '오류표시':     v('error','warning','cross','exclamation','bug'),
  '성공표시':     v('success','check','done','complete','green'),
  '정보표시':     v('info','question','help','circle'),
  '잠그기':       v('lock','security','key','password','protect'),
  '열기잠금':     v('unlock','key','lock','open','security'),

  // ━━━ 사람/신체 동의어 ━━━
  '유저':         v('user','person','account','profile'),
  '사용자':       v('user','person','account','profile'),
  '회원':         v('user','person','account','member'),
  '고객':         v('customer','user','person','service'),
  '환자':         v('patient','medical','person','hospital'),
  '학생':         v('student','school','person','education'),
  '선생':         v('teacher','education','person','school'),
  '의사':         v('doctor','medical','person','hospital'),
  '경찰관':       v('police','officer','person','badge'),
  '소방관':       v('firefighter','person','emergency','fire'),
  '군인':         v('soldier','military','person'),
  '판사':         v('judge','court','person','law'),
  '피고인':       v('person','court','law'),
  '노동자':       v('worker','person','work','construction'),
  '직원':         v('employee','worker','person','office','work'),
  '임원':         v('officer','executive','person','business'),
  '과학자':       v('scientist','lab','person','research'),
  '예술가':       v('artist','art','person','creative'),
  '운동선수':     v('athlete','sport','person','fitness','run'),
  '어린이':       v('child','baby','person','young','kid'),
  '청년':         v('young','person','student','adult'),
  '노인':         v('older','senior','person','age'),
  '장애인':       v('wheelchair','disability','accessibility','person'),

  // ━━━ 몸/신체부위 ━━━
  '눈(신체)':     v('eye','vision','sight','face'),
  '귀(신체)':     v('ear','hearing','sound','face'),
  '코(신체)':     v('nose','smell','face','body'),
  '입(신체)':     v('mouth','speech','talk','face'),
  '이빨':         v('tooth','dental','health','face'),
  '혀':           v('tongue','taste','mouth','face'),
  '손(신체)':     v('hand','finger','touch','gesture'),
  '발':           v('foot','walk','shoe','body'),
  '머리카락':     v('hair','head','face'),
  '두뇌':         v('brain','think','intelligence','mind'),
  '심장(신체)':   v('heart','pulse','medical','health'),
  '근육':         v('muscle','fitness','strong','body','biceps'),
  '뼈':           v('bone','medical','health','body'),
  '혈액':         v('blood','medical','health','red'),
  '피부':         v('skin','face','health','body'),

  // ━━━ 동물 보충 ━━━
  '강아지':       v('dog','puppy','pet','animal','paw'),
  '고양이':       v('cat','kitten','pet','animal'),
  '물고기':       v('fish','pet','ocean','water','animal'),
  '새(동물)':     v('bird','flight','nature','animal'),
  '말(동물)':     v('horse','animal','sport'),
  '소':           v('cow','animal','farm','food'),
  '돼지':         v('pig','animal','farm','food'),
  '닭':           v('chicken','animal','farm','food'),
  '양':           v('sheep','animal','farm'),
  '토끼':         v('rabbit','bunny','animal','pet'),
  '곰':           v('bear','animal','nature','teddy'),
  '사자':         v('lion','animal','wild','king'),
  '호랑이':       v('tiger','animal','wild','stripe'),
  '코끼리':       v('elephant','animal','big','wild'),
  '원숭이':       v('monkey','animal','wild','primate'),
  '벌':           v('bee','insect','flower','nature','honey'),
  '나비':         v('butterfly','insect','nature','flower'),
  '개구리':       v('frog','animal','water','nature'),
  '거북이':       v('turtle','animal','slow','nature'),
  '뱀':           v('snake','animal','wild','reptile'),
  '공룡':         v('dinosaur','animal','ancient'),
  '상어':         v('shark','fish','ocean','danger'),
  '고래':         v('whale','fish','ocean','big'),
  '문어':         v('octopus','ocean','animal'),
  '게':           v('crab','ocean','food','animal'),
  '새우':         v('shrimp','seafood','food','ocean'),

  // ━━━ 음식 상세 ━━━
  '고기요리':     v('food','meat','cook','restaurant'),
  '해산물':       v('seafood','fish','food','ocean'),
  '국수':         v('noodle','food','eat','restaurant'),
  '라면':         v('noodle','food','eat','hot'),
  '스시':         v('sushi','japanese','food','fish'),
  '타코':         v('taco','food','eat','mexican'),
  '파스타':       v('pasta','food','eat','italian'),
  '샐러드':       v('salad','food','healthy','vegetable'),
  '샌드위치':     v('sandwich','food','bread','eat'),
  '도넛':         v('doughnut','food','sweet','bakery'),
  '머핀':         v('muffin','food','sweet','bakery'),
  '초콜릿':       v('chocolate','food','sweet','candy'),
  '사탕':         v('candy','sweet','food','sugar'),
  '시럽':         v('syrup','sweet','food','bottle'),
  '소금':         v('salt','food','season','cook'),
  '후추':         v('pepper','food','season','cook'),
  '오일':         v('oil','food','cook','bottle'),
  '버터':         v('butter','food','cook','dairy'),
  '치즈':         v('cheese','food','dairy','eat'),
  '우유':         v('milk','drink','dairy','food'),
  '요거트':       v('yogurt','food','dairy','health'),
  '꿀':           v('honey','food','bee','sweet'),
  '잼':           v('jam','food','sweet','spread'),
  '소스':         v('sauce','food','cook','bottle'),
  '수프':         v('soup','food','hot','bowl'),
  '스테이크':     v('steak','meat','food','restaurant'),
  '바베큐':       v('bbq','food','fire','outdoor','cook'),
  '파이':         v('pie','food','sweet','bake'),
  '와플':         v('waffle','food','sweet','breakfast'),
  '팬케이크':     v('pancake','food','sweet','breakfast'),
  '오믈렛':       v('egg','food','cook','breakfast'),
  '토스트':       v('toast','food','bread','breakfast'),
  '씨리얼':       v('cereal','food','breakfast','bowl'),
  '에스프레소':   v('coffee','drink','cup','cafe'),
  '라테':         v('coffee','milk','drink','cafe'),
  '카푸치노':     v('coffee','milk','drink','cafe'),
  '밀크티':       v('tea','milk','drink','cup'),
  '주스음료':     v('juice','drink','fruit','glass'),
  '탄산음료':     v('soda','drink','fizzy','glass'),
  '에너지드링크': v('energy','drink','can','boost'),

  // ━━━ 쇼핑/패션 ━━━
  '옷':           v('clothing','shirt','fashion','wear'),
  '신발':         v('shoe','footwear','fashion','walk'),
  '가방(패션)':   v('bag','handbag','fashion','accessory'),
  '지갑(패션)':   v('wallet','purse','fashion','money'),
  '벨트':         v('belt','fashion','clothing','waist'),
  '넥타이':       v('tie','fashion','formal','suit'),
  '스카프':       v('scarf','fashion','clothing','winter'),
  '장갑':         v('gloves','fashion','hand','winter'),
  '양말':         v('sock','clothing','foot','fashion'),
  '팬티':         v('underwear','clothing','fashion'),
  '자켓':         v('jacket','coat','clothing','fashion'),
  '코트(옷)':     v('coat','clothing','winter','fashion'),
  '원피스':       v('dress','clothing','fashion','woman'),
  '치마':         v('skirt','clothing','fashion','woman'),
  '바지':         v('pants','clothing','fashion','wear'),
  '반바지':       v('shorts','clothing','fashion','summer'),
  '운동복':       v('sports','clothing','fitness','wear'),
  '잠옷':         v('sleep','clothing','night','pajama'),
  '수영복':       v('swim','clothing','beach','sport'),
  '정장':         v('suit','tuxedo','formal','business'),
  '모자(패션)':   v('hat','cap','fashion','head'),
  '안경(패션)':   v('glasses','eyewear','fashion','vision'),
  '시계(패션)':   v('watch','wrist','fashion','time'),
  '반지':         v('ring','jewelry','fashion','finger'),
  '목걸이':       v('necklace','jewelry','fashion','neck'),
  '귀걸이':       v('earring','jewelry','fashion','ear'),
  '팔찌':         v('bracelet','jewelry','fashion','wrist'),
  '브로치':       v('pin','jewelry','fashion','badge'),

  // ━━━ 집/인테리어 상세 ━━━
  '책상':         v('desk','table','furniture','office'),
  '선반(인테리어)':v('shelf','storage','furniture','home'),
  '옷장':         v('closet','wardrobe','furniture','clothing'),
  '서랍':         v('drawer','furniture','storage','home'),
  '냉장고':       v('refrigerator','cold','kitchen','home'),
  '세탁기':       v('washer','laundry','clean','home'),
  '에어컨':       v('aircon','cooling','home','temperature'),
  '히터':         v('heater','heating','home','temperature'),
  '선풍기':       v('fan','cooling','home','wind'),
  '청소기':       v('vacuum','clean','home','dust'),
  '다리미':       v('iron','clean','clothing','home'),
  '수도꼭지':     v('faucet','water','kitchen','bathroom'),
  '샤워기':       v('shower','water','bathroom','clean'),
  '거울(인테리어)':v('mirror','reflection','bathroom','home'),
  '커튼':         v('curtains','window','home','fabric'),
  '카펫':         v('carpet','floor','home','fabric'),
  '쿠션':         v('cushion','sofa','home','soft'),
  '시계(인테리어)':v('clock','wall','time','home'),
  '그림액자':     v('frame','picture','wall','home'),
  '화분':         v('plant','flower','pot','home'),

  // ━━━ 교통수단 상세 ━━━
  '택시앱':       v('taxi','car','map','location'),
  '공유차':       v('car','share','rental','drive'),
  '전기차':       v('electric','car','vehicle','charging'),
  'SUV':          v('car','vehicle','big','road'),
  '트럭화물':     v('truck','cargo','delivery','transport'),
  '화물선':       v('ship','cargo','delivery','ocean'),
  '컨테이너선':   v('ship','cargo','container','ocean'),
  '유람선':       v('cruise','ship','travel','ocean'),
  '잠수함':       v('submarine','ocean','military','water'),
  '헬리콥터':     v('helicopter','fly','air','transport'),
  '열기구':       v('balloon','air','fly','travel'),
  '패러글라이딩': v('fly','air','wing','sport'),
  '요트':         v('sailboat','yacht','ocean','travel'),
  '카누':         v('canoe','water','sport','paddle'),
  '킥보드':       v('scooter','electric','transport','city'),
  '전동휠':       v('wheel','electric','transport','balance'),
  '케이블카':     v('cable','transport','mountain','travel'),
  '모노레일':     v('rail','train','transport','city'),
  '고속도로':     v('road','highway','car','speed','fast'),
  '주차빌딩':     v('parking','building','car','garage'),

  // ━━━ 스포츠/레저 상세 ━━━
  '마라톤':       v('run','marathon','sport','fitness','flag'),
  '트라이애슬론': v('swim','bike','run','sport','fitness'),
  '암벽등반':     v('climbing','rock','sport','mountain'),
  '스쿠버다이빙': v('diving','swim','ocean','sport'),
  '패러슈트':     v('parachute','fly','air','sport'),
  '양궁':         v('archery','bow','arrow','sport'),
  '펜싱':         v('sword','sport','shield','fight'),
  '유도':         v('judo','sport','martial','person'),
  '태권도':       v('martial','sport','person','kick'),
  '레슬링':       v('wrestling','sport','person','fight'),
  '수상스키':     v('ski','water','sport','boat'),
  '서핑보드':     v('surfing','board','ocean','wave','sport'),
  '윈드서핑':     v('surfing','wind','ocean','sport'),
  '파쿠르':       v('run','jump','urban','sport'),
  '줄넘기':       v('jump','rope','fitness','exercise'),
  '훌라후프':     v('circle','ring','sport','exercise'),
  '덤벨':         v('weight','dumbbell','fitness','gym'),
  '바벨':         v('weight','bar','fitness','gym'),
  '수영장':       v('pool','swim','water','sport'),
  '경기장':       v('stadium','sport','building'),

  // ━━━ 여행/관광 상세 ━━━
  '해외여행':     v('airplane','travel','passport','world'),
  '국내여행':     v('car','travel','map','bus'),
  '배낭여행자':   v('backpack','person','travel','hike'),
  '단체관광':     v('people','travel','bus','group'),
  '크루즈여행':   v('ship','cruise','travel','ocean'),
  '에어비앤비':   v('home','bed','travel','person'),
  '카페':         v('coffee','cafe','food','cup','restaurant'),
  '편의점':       v('store','convenience','shop','24'),
  '마트':         v('store','shopping','cart','building'),
  '백화점':       v('store','building','shopping','fashion'),
  '시장':         v('store','market','shop','food'),
  '박물관':       v('museum','building','art','history'),
  '미술관':       v('art','gallery','museum','building'),
  '도서관(건물)': v('library','building','book','education'),
  '스포츠센터':   v('sport','building','fitness','gym'),
  '영화관':       v('movie','cinema','screen','entertainment'),
  '공연장':       v('theater','music','entertainment','stage'),
  '테마파크':     v('park','fun','entertainment','ferris'),
  '해수욕장':     v('beach','ocean','swim','summer'),
  '스키장':       v('ski','snow','mountain','sport'),

  // ━━━ 직장/비즈니스 상세 ━━━
  '스타트업':     v('startup','rocket','business','idea'),
  '대기업':       v('building','business','office','enterprise'),
  '중소기업':     v('building','business','office','small'),
  '프리랜서':     v('person','work','laptop','free'),
  '재택근무':     v('home','work','laptop','wifi'),
  '원격근무':     v('remote','work','laptop','wifi'),
  '팀협업':       v('people','team','collaboration','work'),
  '업무분배':     v('assign','task','people','work'),
  '성과평가':     v('chart','review','star','report','rating'),
  '인사관리':     v('people','user','management','office'),
  '고객서비스':   v('service','customer','help','support'),
  '마케팅':       v('marketing','megaphone','chart','star','ads'),
  '광고':         v('ad','megaphone','marketing','star'),
  '홍보':         v('megaphone','broadcast','share','star'),
  '영업':         v('sales','money','handshake','chart'),
  '물류':         v('truck','delivery','box','warehouse'),
  '공급망':       v('chain','supply','truck','warehouse'),
  '품질관리':     v('check','quality','badge','shield'),
  '연구개발':     v('lab','research','brain','science','bulb'),
  '특허':         v('document','shield','badge','certificate'),

  // ━━━ 미디어/콘텐츠 상세 ━━━
  '유튜브채널':   v('youtube','video','play','subscribe'),
  '인스타그램게시물':v('instagram','photo','image','social'),
  '트위터트윗':   v('twitter','message','social','bird'),
  '블로그글':     v('blog','write','post','article'),
  '팟캐스트방송': v('podcast','microphone','audio','headphone'),
  '라디오방송':   v('radio','broadcast','audio','wave'),
  '뉴스레터':     v('mail','newsletter','email','news'),
  '웹툰':         v('comic','cartoon','art','image'),
  '웹소설':       v('book','text','write','story'),
  '게임스트리밍': v('game','stream','live','video','twitch'),
  '영상편집':     v('video','edit','cut','film','scissors'),
  '음악제작':     v('music','create','studio','microphone'),
  '사진보정':     v('photo','edit','filter','adjust','camera'),

  // ━━━ 건강/의료 상세 ━━━
  '종합검진':     v('medical','check','health','hospital'),
  '혈압':         v('blood','pressure','medical','heart'),
  '혈당':         v('blood','glucose','medical','syringe'),
  '콜레스테롤':   v('blood','medical','health','heart'),
  '심전도':       v('heart','pulse','medical','chart'),
  '엑스레이':     v('xray','medical','scan','hospital'),
  'MRI':          v('scan','medical','brain','hospital'),
  'CT스캔':       v('scan','medical','hospital','body'),
  '수술':         v('medical','knife','hospital','doctor'),
  '입원':         v('hospital','bed','medical','person'),
  '퇴원':         v('hospital','door','medical','check'),
  '응급실':       v('emergency','hospital','ambulance','medical'),
  '약처방':       v('pill','prescription','medical','document'),
  '주사':         v('syringe','needle','medical','vaccine'),
  '수혈':         v('blood','medical','hospital','transfer'),
  '헌혈':         v('blood','heart','medical','donation'),
  '장기기증':     v('heart','medical','donation','person'),
  '재활치료':     v('medical','fitness','recovery','person'),
  '심리상담':     v('brain','person','therapy','speech'),
  '정신건강':     v('brain','health','mind','heart'),

  // ━━━ 환경/에너지 ━━━
  '친환경':       v('leaf','green','nature','recycle','eco'),
  '탄소':         v('carbon','environment','pollution','cloud'),
  '온난화':       v('hot','sun','globe','warning','thermometer'),
  '해양오염':     v('ocean','pollution','warning','fish','water'),
  '대기오염':     v('air','pollution','mask','cloud','warning'),
  '쓰레기분리':   v('trash','recycle','bin','sort','clean'),
  '태양에너지':   v('solar','sun','energy','power','panel'),
  '풍력에너지':   v('wind','energy','power','turbine','fan'),
  '수력에너지':   v('water','energy','power','wave'),
  '원자력':       v('nuclear','energy','power','warning','atom'),
  '절전':         v('save','power','battery','energy','sleep'),
  '에너지효율':   v('efficiency','energy','power','bolt','check'),

  // ━━━ 법률/행정 ━━━
  '법원':         v('court','justice','building','hammer','law'),
  '판결':         v('judge','law','document','check','court'),
  '소송':         v('law','document','person','court'),
  '변호사':       v('law','person','briefcase','document'),
  '헌법':         v('document','law','shield','country'),
  '규정':         v('document','rule','law','list'),
  '정책':         v('document','policy','law','government'),
  '법령':         v('document','law','government','book'),
  '면허증':       v('license','document','card','certificate'),
  '여권(문서)':   v('passport','document','travel','id'),
  '주민등록':     v('id','document','person','card'),
  '인감도장':     v('stamp','seal','document','signature'),
  '공증':         v('document','certified','stamp','official'),
  '세금신고':     v('tax','document','money','report','file'),
  '등기':         v('document','register','official','stamp'),

  // ━━━ 교육/학습 상세 ━━━
  '초등학교':     v('school','education','child','book'),
  '중학교':       v('school','education','student','book'),
  '고등학교':     v('school','education','student','study'),
  '대학교':       v('university','education','graduation','building'),
  '대학원':       v('graduate','education','book','research'),
  '어학원':       v('language','education','book','translate'),
  '학원':         v('school','education','study','building'),
  '과외':         v('person','education','study','book'),
  '강사':         v('teacher','education','person','presentation'),
  '교수':         v('professor','education','person','book'),
  '논문':         v('document','research','education','write'),
  '리포트':       v('report','document','education','write'),
  '발표(학교)':   v('presentation','education','person','slide'),
  '실험':         v('lab','experiment','flask','beaker','science'),
  '과학프로젝트': v('science','project','lab','education'),
  '수학문제':     v('math','problem','pencil','education'),
  '영어공부':     v('english','language','book','education'),

  // ━━━ 종교/문화 ━━━
  '교회(종교)':   v('church','cross','religion','building'),
  '성당':         v('church','cross','religion','building'),
  '절':           v('temple','religion','building','asia'),
  '모스크':       v('mosque','islam','religion','building'),
  '기도':         v('prayer','religion','hand','cross'),
  '성경':         v('book','cross','religion','read'),
  '십자가':       v('cross','religion','church','symbol'),
  '별(종교)':     v('star','religion','jewish','symbol'),
  '달(이슬람)':   v('moon','crescent','religion','islamic'),
  '명상':         v('meditation','person','peace','lotus'),
  '요가':         v('yoga','lotus','fitness','person','peace'),
  '불교':         v('lotus','temple','religion','asia'),
  '크리스마스트리':v('tree','christmas','star','decoration'),
  '할로윈':       v('ghost','skull','halloween','pumpkin'),
  '발렌타인':     v('heart','love','valentine','gift'),
  '추석':         v('moon','family','food','holiday'),
  '설날':         v('celebration','family','food','new'),

  // ━━━ 지리/지역 ━━━
  '아시아':       v('asia','map','globe','region'),
  '유럽':         v('europe','map','globe','region'),
  '아메리카':     v('americas','map','globe','region'),
  '아프리카':     v('africa','map','globe','region'),
  '오세아니아':   v('ocean','map','globe','region'),
  '북극':         v('north','ice','snow','cold','globe'),
  '남극':         v('south','ice','snow','cold','globe'),
  '태평양':       v('ocean','pacific','water','map'),
  '대서양':       v('ocean','atlantic','water','map'),
  '인도양':       v('ocean','indian','water','map'),
  '히말라야':     v('mountain','himalaya','snow','nature'),
  '사막':         v('desert','sand','sun','hot','nature'),
  '열대우림':     v('forest','tropical','nature','rain','tree'),
  '초원':         v('grassland','nature','green','field'),
  '섬나라':       v('island','ocean','country','map'),

  // ━━━ 수학/과학 ━━━
  '덧셈':         v('plus','add','math','calculator'),
  '뺄셈':         v('minus','subtract','math','calculator'),
  '곱셈':         v('multiply','times','math','calculator'),
  '나눗셈':       v('divide','math','calculator','fraction'),
  '분수':         v('fraction','math','divide','number'),
  '소수':         v('decimal','point','math','number'),
  '제곱':         v('square','math','power','number'),
  '제곱근':       v('root','math','square','calculate'),
  '미적분':       v('calculus','math','chart','formula'),
  '방정식':       v('equation','math','formula','calculate'),
  '그래프(수학)': v('graph','chart','math','data','coordinate'),
  '통계(수학)':   v('statistics','data','chart','math'),
  '확률':         v('percent','probability','math','chart'),
  '원소':         v('element','chemistry','science','atom'),
  '주기율표':     v('periodic','chemistry','science','table'),
  '전자':         v('electron','atom','science','energy'),
  '원자핵':       v('atom','nucleus','science','energy','nuclear'),
  '중력':         v('gravity','physics','arrow','down','science'),
  '빛':           v('light','ray','bulb','sun','flash'),
  '음파':         v('sound','wave','audio','frequency'),
  '전자기파':     v('wave','radio','frequency','energy'),
  '빅뱅':         v('universe','star','explosion','science'),

  // ━━━ 색상 상세 ━━━
  '색깔':         v('color','palette','paint','design'),
  '원색':         v('color','primary','red','blue','yellow'),
  '무채색':       v('grayscale','black','white','gray'),
  '형광색':       v('neon','bright','color','glow'),
  '파스텔':       v('pastel','soft','color','light'),
  '골드':         v('gold','yellow','star','luxury','coin'),
  '실버':         v('silver','gray','medal','metal'),
  '브론즈':       v('bronze','medal','metal','award'),
  '투명':         v('transparent','clear','glass','opacity'),
  '반투명':       v('opacity','transparent','blur','glass'),

  // ━━━ 숫자/측정 상세 ━━━
  '0~9':          v('number','digit','count','numeric'),
  '두자리수':     v('number','digit','count'),
  '세자리수':     v('number','digit','count'),
  '소수점숫자':   v('decimal','number','dot'),
  '음수':         v('minus','negative','number','math'),
  '양수':         v('plus','positive','number','math'),
  '무한':         v('infinity','loop','endless','math'),
  '길이':         v('ruler','measure','length','width'),
  '면적':         v('area','measure','square','surface'),
  '부피':         v('volume','measure','cube','3d'),
  '질량':         v('weight','mass','scale','measure'),
  '밀도':         v('density','measure','weight','volume'),
  '압력':         v('pressure','measure','gauge','force'),
  '속도':         v('speed','fast','measure','dash'),
  '가속도':       v('speed','increase','fast','measure'),
  '주파수':       v('frequency','wave','audio','measure'),
  '전압':         v('voltage','electric','power','measure'),
  '전류':         v('current','electric','power','measure'),
  '전력':         v('power','electric','energy','bolt'),

  // ━━━ 기술/개발 상세 ━━━
  '프론트엔드':   v('web','code','design','html','css'),
  '백엔드':       v('server','database','code','api'),
  '풀스택':       v('server','web','code','stack','full'),
  '데브옵스':     v('deploy','server','automation','code'),
  '애자일':       v('sprint','agile','task','team'),
  '스크럼':       v('team','sprint','task','people'),
  '칸반보드':     v('kanban','board','task','card'),
  '버전관리':     v('git','version','history','code'),
  '코드리뷰':     v('review','code','check','person'),
  '테스트코드':   v('test','code','check','bug'),
  '빌드':         v('build','compile','code','server'),
  '배포(개발)':   v('deploy','server','cloud','code'),
  '모니터링':     v('monitor','analytics','chart','server'),
  '로그(개발)':   v('log','code','server','file','list'),
  '디버깅':       v('debug','bug','code','fix','tool'),
  '리팩토링':     v('refactor','code','clean','organize'),
  '문서화':       v('document','code','write','api'),
  '컴파일':       v('compile','code','build','gear'),
  '패키지':       v('package','npm','code','box','folder'),
  '라이브러리(개발)':v('library','code','package','folder'),
  '프레임워크':   v('framework','code','structure','build'),
  '미들웨어':     v('middleware','server','code','layer'),
  '캐시':         v('cache','speed','storage','server'),
  '쿠키':         v('cookie','browser','data','privacy'),
  '세션':         v('session','user','login','security'),
  '토큰(인증)':   v('token','key','security','auth','lock'),
  'OAuth':        v('auth','login','key','security','lock'),
  '웹소켓':       v('socket','network','connection','web'),
  '마이크로서비스':v('service','server','cloud','code','api'),
  '도메인(개발)': v('domain','server','web','url'),
  '데이터베이스': v('database','data','server','storage'),
  'SQL':          v('database','query','data','table','sql'),
  'NoSQL':        v('database','document','data','server'),
  '엔드포인트':   v('endpoint','api','server','url'),
  '페이로드':     v('data','package','send','api'),
  '쿼리':         v('query','database','search','data'),
  '인덱스':       v('index','list','search','data','order'),
  '스키마':       v('schema','database','structure','data'),

  // ━━━ 소셜미디어 상세 ━━━
  '팔로우하기':   v('follow','person','social','add'),
  '언팔로우':     v('unfollow','person','social','remove'),
  '구독하기':     v('subscribe','bell','youtube','follow'),
  '구독취소':     v('unsubscribe','bell','off','remove'),
  '좋아요누르기': v('like','heart','thumb','social'),
  '싫어요':       v('dislike','thumb','down','social'),
  '리트윗':       v('retweet','share','twitter','social'),
  '멘션하기':     v('mention','at','social','person'),
  '해시태그달기': v('hashtag','tag','social','search'),
  '스토리올리기': v('story','circle','social','image'),
  '라이브켜기':   v('live','broadcast','video','social'),
  '다이렉트메시지':v('dm','message','mail','social','person'),
  '커뮤니티':     v('community','people','group','social'),
  '포럼':         v('forum','chat','people','community'),
  '리뷰작성':     v('review','star','write','comment'),
  '신고하기':     v('report','warning','flag','alert'),
  '차단하기':     v('block','ban','shield','person'),

  // ━━━ 게임/엔터테인먼트 상세 ━━━
  '게임캐릭터':   v('character','game','person','avatar'),
  '게임아이템':   v('item','game','star','badge','sword'),
  '게임맵':       v('map','game','location','world'),
  '인벤토리':     v('inventory','bag','box','storage','game'),
  '퀘스트':       v('quest','task','game','flag','target'),
  '레이드':       v('raid','game','battle','group','sword'),
  '길드':         v('guild','people','group','game','shield'),
  '아이템강화':   v('upgrade','item','star','game','level'),
  '경험치':       v('experience','level','chart','star','game'),
  '레벨업':       v('level','up','arrow','star','game'),
  '게임오버':     v('gameover','skull','dead','game','error'),
  '채팅(게임)':   v('chat','message','game','bubble'),
  '음소거(게임)': v('mute','volume','game','off'),
  '설정(게임)':   v('settings','gear','game','menu'),

  // ━━━ 프린트/인쇄 상세 ━━━
  '프린터오류':   v('printer','error','warning','fix'),
  '잉크카트리지': v('ink','printer','cartridge','color'),
  '인쇄미리보기': v('print','preview','document','view'),
  '스캔변환':     v('scan','convert','document','digital'),
  '복합기':       v('printer','scanner','copy','machine'),
  '팩스':         v('fax','paper','document','send'),

  // ━━━ 시간 상세 ━━━
  '몇시':         v('clock','time','hour','watch'),
  '분':           v('clock','time','minute','watch'),
  '초':           v('clock','time','second','stopwatch'),
  '시간대':       v('timezone','clock','globe','world'),
  '표준시':       v('timezone','clock','time','world'),
  '듀레이션':     v('duration','time','clock','play'),
  '타이머설정':   v('timer','clock','set','alarm'),
  '카운트다운':   v('countdown','timer','clock','arrow','number'),
  '업타임':       v('uptime','server','clock','check'),
  '만료날짜':     v('expire','calendar','clock','warning'),

  // ━━━ 사진/이미지 상세 ━━━
  '셀카':         v('selfie','camera','person','photo'),
  '단체사진':     v('people','camera','photo','group'),
  '인물사진':     v('person','portrait','camera','photo'),
  '풍경사진':     v('landscape','camera','photo','nature'),
  '항공사진':     v('aerial','drone','camera','photo','map'),
  '흑백사진':     v('grayscale','photo','bw','camera'),
  '원본사진':     v('original','photo','image','raw'),
  '편집사진':     v('edit','photo','filter','adjust'),
  '사진앨범':     v('album','photo','gallery','folder'),
  '슬라이드쇼':   v('slideshow','photo','gallery','play'),
  '이미지공유':   v('image','share','social','upload'),
  '스크린샷찍기': v('screenshot','screen','capture','camera'),
  '이미지변환':   v('image','convert','format','file'),
  '이미지압축':   v('image','compress','zip','size'),

};

let added = 0, skipped = 0;
for (const [k, arr] of Object.entries(bulk2)) {
  if (arr.length === 0) { skipped++; continue; }
  if (!ko[k]) { ko[k] = arr; added++; }
}

const sorted = {};
for (const key of Object.keys(ko).sort()) sorted[key] = ko[key];
fs.writeFileSync(path.join(__dirname,'..','ko_dict.json'), JSON.stringify(sorted, null, 2));
console.log(`추가: ${added} / 스킵: ${skipped} / 최종: ${Object.keys(sorted).length}`);
