#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const ko = JSON.parse(fs.readFileSync(path.join(__dirname,'..','ko_dict.json'),'utf8'));
const words = new Set(JSON.parse(fs.readFileSync(path.join(__dirname,'..','data','icon_words.json'),'utf8')).map(w=>w.word));
const v = (...arr) => arr.filter(w => words.has(w));

const bulk5 = {

  // ━━━ 자주 쓰는 복합 검색어 ━━━
  '화살표위':      v('arrow','up','chevron','top'),
  '화살표아래':    v('arrow','down','chevron','bottom'),
  '화살표왼쪽':   v('arrow','left','chevron','back'),
  '화살표오른쪽': v('arrow','right','chevron','forward'),
  '원형화살표':   v('rotate','circle','refresh','loop'),
  '양방향화살표': v('arrows','bidirectional','exchange','swap'),
  '점세개(가로)': v('dots','horizontal','ellipsis','more'),
  '점세개(세로)': v('dots','vertical','menu','more'),
  '더보기버튼':   v('more','dots','ellipsis','menu'),
  '닫기버튼':     v('close','x','exit','cancel'),
  '확인버튼':     v('check','confirm','done','ok'),
  '취소버튼':     v('cancel','close','x','stop'),
  '뒤로버튼':     v('back','arrow','previous','navigate'),
  '앞으로버튼':   v('forward','arrow','next','navigate'),
  '홈버튼':       v('home','house','main','start'),
  '메뉴버튼':     v('menu','hamburger','list','navigation'),
  '검색버튼':     v('search','magnifying','find','input'),
  '플러스버튼':   v('plus','add','create','new'),
  '마이너스버튼': v('minus','remove','delete','subtract'),
  '공유버튼':     v('share','export','send','social'),
  '편집버튼':     v('edit','pen','pencil','modify'),
  '삭제버튼':     v('delete','trash','remove','bin'),
  '저장버튼':     v('save','disk','floppy','check'),
  '설정버튼':     v('settings','gear','cog','configure'),
  '알림버튼':     v('notification','bell','alert','badge'),
  '즐겨찾기버튼': v('favorite','star','heart','bookmark'),
  '필터버튼':     v('filter','funnel','sort','adjust'),
  '정렬버튼':     v('sort','list','order','arrange'),
  '다운로드버튼': v('download','arrow','receive','file'),
  '업로드버튼':   v('upload','arrow','send','cloud'),
  '새로고침버튼': v('refresh','reload','sync','update'),
  '전체선택':     v('select','all','check','list'),
  '선택해제':     v('deselect','uncheck','clear','list'),

  // ━━━ 아이콘 스타일 검색 ━━━
  '아웃라인아이콘':v('outline','border','stroke','icon'),
  '채워진아이콘':  v('filled','solid','color','icon'),
  '선형아이콘':   v('line','stroke','thin','icon'),
  '굵은아이콘':   v('bold','thick','heavy','icon'),
  '컬러아이콘':   v('color','colorful','icon','image'),
  '흑백아이콘':   v('black','white','mono','icon'),
  '둥근아이콘':   v('round','circle','smooth','icon'),
  '각진아이콘':   v('sharp','corner','square','icon'),
  '그라디언트아이콘':v('gradient','color','design','icon'),
  '듀오톤아이콘': v('duotone','two','color','icon'),
  '플랫아이콘':   v('flat','simple','clean','icon'),
  '3D아이콘':     v('3d','depth','shadow','icon'),
  '미니멀아이콘': v('minimal','simple','clean','basic'),
  '레트로아이콘': v('retro','vintage','old','classic'),

  // ━━━ 크기 표현 ━━━
  '아주작은':     v('tiny','mini','small','micro'),
  '작은':         v('small','little','mini','low'),
  '보통크기':     v('medium','normal','standard','regular'),
  '큰':           v('large','big','max','full'),
  '아주큰':       v('huge','xlarge','big','full'),
  '16px':         v('small','tiny','icon','pixel'),
  '24px':         v('icon','pixel','size','standard'),
  '32px':         v('icon','medium','pixel','size'),
  '48px':         v('icon','large','pixel','size'),
  '64px':         v('icon','xlarge','pixel','size'),

  // ━━━ 위치/방향 표현 ━━━
  '상단왼쪽':     v('top','left','corner','align'),
  '상단오른쪽':   v('top','right','corner','align'),
  '하단왼쪽':     v('bottom','left','corner','align'),
  '하단오른쪽':   v('bottom','right','corner','align'),
  '정중앙':       v('center','middle','align','focus'),
  '우측정렬':     v('align','right','text','layout'),
  '좌측정렬':     v('align','left','text','layout'),
  '가운데정렬':   v('align','center','text','layout'),
  '양쪽정렬':     v('justify','align','text','layout'),
  '위정렬':       v('align','top','vertical','layout'),
  '아래정렬':     v('align','bottom','vertical','layout'),
  '세로가운데':   v('align','middle','vertical','layout'),
  '간격균등':     v('distribute','space','equal','layout'),
  '가로간격':     v('space','horizontal','distribute','layout'),
  '세로간격':     v('space','vertical','distribute','layout'),

  // ━━━ 날씨 아이콘 상세 ━━━
  '맑은날씨':     v('sunny','clear','sun','weather'),
  '구름많음':     v('cloudy','cloud','overcast','weather'),
  '비오는날':     v('rain','rainy','cloud','weather'),
  '눈오는날':     v('snow','snowy','cold','weather'),
  '흐린날':       v('overcast','cloud','gray','weather'),
  '폭풍우':       v('storm','thunder','rain','lightning','weather'),
  '안개낀날':     v('fog','foggy','mist','weather'),
  '바람부는날':   v('wind','windy','breeze','weather'),
  '더운날':       v('hot','sun','heat','weather','temperature'),
  '추운날':       v('cold','freeze','ice','weather','temperature'),
  '비바람':       v('rain','wind','storm','weather'),
  '눈바람':       v('snow','wind','blizzard','weather'),
  '천둥번개':     v('thunder','lightning','bolt','weather'),
  '일출':         v('sunrise','sun','morning','horizon'),
  '일몰':         v('sunset','sun','evening','horizon'),
  '달빛':         v('moon','night','light','star'),
  '별이많은밤':   v('star','night','moon','sky'),
  '무지개':       v('rainbow','color','rain','sun'),

  // ━━━ 계절/자연 상세 ━━━
  '벚꽃':         v('flower','cherry','pink','spring'),
  '단풍':         v('leaf','autumn','fall','color','red'),
  '낙엽':         v('leaf','fall','autumn','nature'),
  '새싹':         v('sprout','seedling','green','spring','plant'),
  '눈사람':       v('snowman','snow','winter','cold'),
  '모래사장':     v('sand','beach','summer','sun'),
  '파도타기':     v('wave','surf','ocean','beach'),
  '일출해변':     v('beach','sunrise','ocean','morning'),
  '산정상':       v('mountain','peak','top','nature'),
  '계곡':         v('valley','water','mountain','nature'),
  '폭포':         v('waterfall','water','nature','fall'),
  '강가':         v('river','water','nature','landscape'),
  '호수':         v('lake','water','nature','reflection'),
  '사막모래':     v('desert','sand','hot','sun','nature'),
  '열대우림':     v('jungle','tropical','tree','rain','nature'),
  '극지방':       v('arctic','ice','snow','cold','polar'),
  '화산':         v('volcano','fire','mountain','lava','eruption'),
  '동굴':         v('cave','dark','nature','underground'),
  '암석':         v('rock','stone','mountain','nature'),
  '협곡':         v('canyon','cliff','nature','valley'),

  // ━━━ 우주/천문 ━━━
  '우주':         v('space','star','universe','rocket','planet'),
  '별자리':       v('constellation','star','space','night'),
  '은하수':       v('galaxy','star','space','universe'),
  '혜성':         v('comet','star','space','tail'),
  '소행성':       v('asteroid','space','rock','planet'),
  '블랙홀':       v('blackhole','space','dark','gravity'),
  '태양계':       v('solar','system','planet','sun','space'),
  '화성':         v('mars','planet','red','space'),
  '토성':         v('saturn','planet','ring','space'),
  '목성':         v('jupiter','planet','space','big'),
  '금성':         v('venus','planet','space','star'),
  '우주탐사':     v('space','explore','rocket','satellite'),
  '우주정거장':   v('station','space','satellite','orbit'),
  '인공위성':     v('satellite','orbit','space','signal'),
  '우주인':       v('astronaut','space','rocket','person'),

  // ━━━ 역사/시대 ━━━
  '고대':         v('ancient','old','history','artifact'),
  '중세':         v('medieval','castle','sword','history'),
  '근대':         v('modern','history','building','clock'),
  '현대':         v('contemporary','modern','city','building'),
  '미래':         v('future','rocket','star','tech','robot'),
  '석기시대':     v('stone','age','history','ancient'),
  '청동기':       v('bronze','medal','ancient','history'),
  '철기':         v('iron','metal','ancient','history'),
  '르네상스':     v('renaissance','art','painting','history'),
  '산업혁명':     v('industry','factory','machine','history'),
  '디지털혁명':   v('digital','tech','computer','revolution'),

  // ━━━ 종류/카테고리 ━━━
  '아이콘팩':     v('pack','collection','icons','folder'),
  '무료아이콘':   v('free','icon','open','download'),
  '유료아이콘':   v('premium','icon','paid','pro'),
  'SVG아이콘':    v('svg','vector','icon','design'),
  'PNG아이콘':    v('png','image','icon','file'),
  '애니메이션아이콘':v('animated','gif','motion','icon'),
  '이모지아이콘': v('emoji','face','emotion','icon'),
  '플랫아이콘팩': v('flat','pack','icon','simple'),
  '소셜아이콘':   v('social','icon','media','brand'),
  '금융아이콘':   v('finance','money','icon','business'),
  '의료아이콘':   v('medical','health','icon','hospital'),
  '교육아이콘':   v('education','school','icon','book'),
  '쇼핑아이콘':   v('shopping','icon','cart','store'),
  '여행아이콘':   v('travel','icon','airplane','map'),
  '음식아이콘':   v('food','icon','eat','restaurant'),
  '스포츠아이콘': v('sport','icon','fitness','ball'),
  '음악아이콘':   v('music','icon','audio','note'),
  '날씨아이콘':   v('weather','icon','cloud','sun'),
  '기술아이콘':   v('tech','icon','code','computer'),

  // ━━━ 숙박/여행 ━━━
  '5성호텔':      v('hotel','star','luxury','premium'),
  '모텔':         v('motel','bed','sleep','hotel'),
  '게스트하우스': v('guesthouse','bed','person','share'),
  '캡슐호텔':     v('capsule','bed','hotel','small'),
  '풀빌라':       v('villa','pool','luxury','travel'),
  '펜션':         v('pension','house','travel','nature'),
  '캠핑카':       v('camper','van','travel','home'),
  '글램핑장':     v('glamping','tent','luxury','nature'),
  '서핑캠프':     v('surf','camp','ocean','beach'),
  '스키리조트':   v('ski','resort','snow','mountain'),
  '골프리조트':   v('golf','resort','sport','luxury'),
  '해양리조트':   v('ocean','resort','beach','pool'),
  '산악리조트':   v('mountain','resort','nature','hiking'),
  '온천':         v('hotspring','water','nature','relax'),
  '스파':         v('spa','massage','relax','health'),
  '수영장이있는호텔':v('hotel','pool','swim','luxury'),

  // ━━━ 레스토랑/카페 ━━━
  '파인다이닝':   v('fine','dining','restaurant','luxury','food'),
  '캐주얼다이닝': v('casual','dining','restaurant','food'),
  '패스트푸드':   v('fast','food','quick','restaurant'),
  '푸드코트':     v('food','court','restaurant','multiple'),
  '뷔페':         v('buffet','food','all','restaurant'),
  '브런치카페':   v('brunch','cafe','food','morning'),
  '디저트카페':   v('dessert','cafe','sweet','food'),
  '베이커리':     v('bakery','bread','food','sweet'),
  '주류바':       v('bar','beer','drink','night'),
  '와인바':       v('wine','bar','drink','restaurant'),
  '칵테일바':     v('cocktail','bar','drink','night'),
  '식품점':       v('grocery','food','store','shop'),
  '편의점음식':   v('convenience','food','quick','store'),
  '배달앱':       v('delivery','app','food','phone'),
  '맛집':         v('restaurant','popular','food','star'),

  // ━━━ 인테리어/집꾸미기 ━━━
  '미니멀인테리어':v('minimal','clean','white','interior'),
  '모던인테리어': v('modern','design','clean','interior'),
  '클래식인테리어':v('classic','vintage','luxury','interior'),
  '북유럽스타일': v('nordic','scandinavian','minimal','interior'),
  '빈티지스타일': v('vintage','retro','old','interior'),
  '인더스트리얼': v('industrial','metal','brick','interior'),
  '내추럴인테리어':v('natural','wood','green','interior'),
  '거실꾸미기':   v('living','room','sofa','decoration'),
  '침실꾸미기':   v('bedroom','bed','decoration','cozy'),
  '주방꾸미기':   v('kitchen','design','decoration','cook'),
  '욕실꾸미기':   v('bathroom','design','decoration','clean'),
  '홈오피스':     v('home','office','desk','work'),
  '조명인테리어': v('lighting','decoration','home','lamp'),
  '식물인테리어': v('plant','decoration','green','home'),
  '아트인테리어': v('art','decoration','frame','wall'),

  // ━━━ 운동/피트니스 상세2 ━━━
  '홈트레이닝':   v('home','workout','fitness','exercise'),
  '헬스장운동':   v('gym','fitness','weights','exercise'),
  '요가매트':     v('yoga','mat','fitness','exercise'),
  '필라테스':     v('pilates','fitness','core','exercise'),
  '크로스핏':     v('crossfit','fitness','workout','intense'),
  '러닝머신':     v('treadmill','run','fitness','indoor'),
  '자전거운동':   v('cycling','bike','fitness','exercise'),
  '수영운동':     v('swimming','pool','fitness','water'),
  '체조':         v('gymnastics','fitness','acrobatics','sport'),
  '유산소운동':   v('cardio','aerobic','run','fitness'),
  '무산소운동':   v('anaerobic','weight','strength','fitness'),
  '인터벌트레이닝':v('interval','training','fitness','run'),
  '스트렝스트레이닝':v('strength','training','weight','fitness'),
  '컨디셔닝':     v('conditioning','fitness','training','exercise'),
  '쿨다운':       v('cooldown','stretch','fitness','relax'),
  '워밍업':       v('warmup','stretch','fitness','prepare'),
  '칼로리소모':   v('calorie','burn','fitness','energy'),
  '체지방':       v('fat','body','fitness','weight'),
  '근육량':       v('muscle','mass','fitness','weight'),
  'BMI':          v('bmi','health','weight','measure'),

  // ━━━ 음악 장르/스타일 ━━━
  '팝음악':       v('pop','music','song','star'),
  '록음악':       v('rock','music','guitar','electric'),
  '재즈음악':     v('jazz','music','trumpet','saxophone'),
  'R&B음악':      v('rnb','music','soul','rhythm'),
  '힙합음악':     v('hiphop','music','rap','beat'),
  '클래식음악':   v('classical','music','orchestra','violin'),
  '전자음악':     v('electronic','music','dj','beat'),
  '컨트리음악':   v('country','music','guitar','western'),
  '레게음악':     v('reggae','music','beat','rhythm'),
  '케이팝':       v('kpop','music','dance','korea'),
  '인디음악':     v('indie','music','alternative','guitar'),
  '포크음악':     v('folk','music','guitar','acoustic'),
  '오페라':       v('opera','music','voice','theater'),
  '발라드':       v('ballad','music','slow','emotional'),

  // ━━━ 소재/재료 ━━━
  '금속':         v('metal','iron','steel','material'),
  '나무재료':     v('wood','timber','material','natural'),
  '플라스틱':     v('plastic','material','synthetic'),
  '유리':         v('glass','transparent','material','clear'),
  '고무':         v('rubber','flexible','material'),
  '가죽':         v('leather','skin','material','bag'),
  '면':           v('cotton','fabric','textile','material'),
  '실크':         v('silk','smooth','luxury','fabric'),
  '울':           v('wool','warm','fabric','material'),
  '다이아몬드재료':v('diamond','gem','luxury','crystal'),
  '보석':         v('gem','jewel','crystal','luxury','diamond'),
  '금':           v('gold','yellow','luxury','coin'),
  '은':           v('silver','metal','shiny','coin'),
  '구리':         v('copper','metal','wire','material'),
  '콘크리트':     v('concrete','building','construction','gray'),
  '벽돌':         v('brick','wall','construction','building'),
  '대리석':       v('marble','stone','luxury','floor'),
  '타일':         v('tile','floor','bathroom','pattern'),

  // ━━━ 세계 음식 ━━━
  '한식':         v('korean','food','rice','traditional'),
  '중식':         v('chinese','food','rice','asian'),
  '일식':         v('japanese','sushi','food','asian'),
  '양식':         v('western','food','restaurant','euro'),
  '인도음식':     v('indian','food','curry','spice'),
  '태국음식':     v('thai','food','spice','asian'),
  '이탈리아음식': v('italian','pizza','pasta','food'),
  '프랑스음식':   v('french','food','restaurant','wine','fancy'),
  '멕시코음식':   v('mexican','taco','food','spice'),
  '중동음식':     v('middle','eastern','food','kebab'),
  '동남아음식':   v('southeast','asian','food','spice'),
  '베트남음식':   v('vietnamese','pho','food','noodle'),
  '터키음식':     v('turkish','food','kebab','middle'),
  '스페인음식':   v('spanish','tapas','food','wine'),
  '그리스음식':   v('greek','food','salad','olive'),

  // ━━━ 일본어/중국어 유입어 ━━━
  '아이템':       v('item','product','thing','object'),
  '레벨':         v('level','stage','rank','up'),
  '포인트':       v('point','star','score','reward'),
  '코스':         v('course','route','meal','education'),
  '세트':         v('set','group','bundle','collection'),
  '클래스':       v('class','category','education','group'),
  '타입':         v('type','category','kind','sort'),
  '카테고리':     v('category','folder','tag','list'),
  '브랜드':       v('brand','logo','badge','company'),
  '스타일':       v('style','design','fashion','theme'),
  '패턴':         v('pattern','design','texture','repeat'),
  '컬러':         v('color','palette','paint','design'),
  '사이즈':       v('size','scale','resize','measure'),
  '옵션':         v('option','settings','choice','select'),
  '모드':         v('mode','settings','theme','switch'),
  '타이머':       v('timer','clock','alarm','countdown'),
  '카운터':       v('counter','number','count','tally'),
  '스코어':       v('score','point','star','game'),
  '랭크':         v('rank','level','star','top'),
  '뱃지':         v('badge','award','medal','star'),
  '트로피':       v('trophy','award','win','gold'),
  '스타':         v('star','favorite','top','rating'),
  '팁':           v('tip','info','help','lightbulb'),
  '가이드':       v('guide','help','document','navigation'),

  // ━━━ 영어 약어 검색 ━━━
  'UI':           v('ui','design','interface','layout'),
  'UX':           v('ux','design','user','experience'),
  'CTA':          v('button','click','action','call'),
  'FAQ':          v('faq','question','help','info'),
  'TOS':          v('terms','document','legal','official'),
  'ETA':          v('time','estimate','clock','arrival'),
  'ASAP':         v('urgent','fast','priority','warning'),
  'TBD':          v('pending','question','unknown','clock'),
  'N/A':          v('empty','none','cross','unavailable'),
  'OTP':          v('otp','password','security','phone'),
  'SSO':          v('sso','login','key','security'),
  'MFA':          v('mfa','security','lock','phone'),
  'GDPR':         v('privacy','legal','shield','data'),
  'SLA':          v('agreement','service','document','check'),
  'MVP':          v('minimum','product','feature','build'),
  'CRM':          v('crm','customer','relationship','data'),
  'ERP':          v('erp','business','system','integrate'),
  'CMS':          v('cms','content','manage','web'),
  'CDN':          v('cdn','network','cloud','fast'),
  'SDK':          v('sdk','code','develop','package'),
  'CLI':          v('cli','terminal','command','code'),

  // ━━━ 한국 특유 아이콘 필요 상황 ━━━
  '태극기':       v('flag','korea','country','symbol'),
  '공공마크':     v('official','symbol','badge','check'),
  '인증마크':     v('verified','badge','check','official'),
  '품질마크':     v('quality','badge','check','star'),
  '환경마크':     v('eco','green','leaf','badge'),
  '안전마크':     v('safety','shield','check','badge'),
  '영양표시':     v('nutrition','label','food','health'),
  '열량표시':     v('calorie','label','food','number'),
  '유통기한':     v('expiry','calendar','date','warning'),
  '원산지':       v('origin','location','flag','map'),
  '제조국':       v('manufacture','country','flag','factory'),
  '성분표시':     v('ingredient','label','info','list'),
  '금연구역':     v('nosmoking','prohibited','warning','sign'),
  '금지표시':     v('prohibited','ban','circle','cross'),
  '주의표시':     v('caution','warning','triangle','alert'),
  '위험표시':     v('danger','warning','skull','alert'),
  '비상구':       v('emergency','exit','door','arrow','green'),
  '소화기':       v('extinguisher','fire','emergency','red'),
  '응급처치':     v('first','aid','medical','cross','emergency'),

  // ━━━ 생활/일상 추가 ━━━
  '커피한잔':     v('coffee','cup','morning','drink'),
  '점심식사':     v('lunch','food','eat','noon','meal'),
  '저녁식사':     v('dinner','food','eat','night','meal'),
  '퇴근길':       v('commute','home','person','road','walk'),
  '출근길':       v('commute','office','person','road','morning'),
  '주말여가':     v('weekend','leisure','free','relax'),
  '명상시간':     v('meditation','quiet','peace','mind'),
  '독서시간':     v('reading','book','quiet','relax'),
  '운동시간':     v('exercise','fitness','clock','routine'),
  '수면시간':     v('sleep','clock','night','bed'),
  '식사시간':     v('meal','clock','food','eat'),
  '공부시간':     v('study','clock','book','education'),
  '취미활동':     v('hobby','leisure','fun','personal'),
  '봉사활동':     v('volunteer','community','heart','person'),
  '종교활동':     v('religion','prayer','community','building'),
  '모임참석':     v('meeting','people','group','attend'),
  '파티참석':     v('party','people','celebration','fun'),
  '행사참여':     v('event','people','participate','calendar'),
  '전시관람':     v('exhibition','art','gallery','view'),
  '공연관람':     v('performance','theater','music','view'),

  // ━━━ 디지털/앱 마케팅 ━━━
  '앱스토어':     v('appstore','apple','download','app'),
  '플레이스토어': v('playstore','android','download','app'),
  '앱다운로드':   v('download','app','phone','arrow'),
  '업데이트알림': v('update','notification','bell','new'),
  '앱리뷰':       v('review','app','star','comment'),
  '앱평점':       v('rating','star','app','review'),
  '인앱구매':     v('purchase','app','money','in-app'),
  '앱권한요청':   v('permission','app','request','security'),
  '앱데이터':     v('data','app','storage','clear'),
  '앱캐시':       v('cache','app','storage','clear'),
  '앱알림설정':   v('notification','app','bell','settings'),
  '위젯추가':     v('widget','add','home','screen'),
  '바로가기추가': v('shortcut','add','home','screen'),
  '앱아이콘변경': v('icon','change','customize','app'),
  '기본앱설정':   v('default','app','settings','configure'),

};

let added = 0, skipped = 0;
for (const [k, arr] of Object.entries(bulk5)) {
  if (arr.length === 0) { skipped++; continue; }
  if (!ko[k]) { ko[k] = arr; added++; }
}

const sorted = {};
for (const key of Object.keys(ko).sort()) sorted[key] = ko[key];
fs.writeFileSync(path.join(__dirname,'..','ko_dict.json'), JSON.stringify(sorted, null, 2));
console.log(`추가: ${added} / 스킵: ${skipped} / 최종: ${Object.keys(sorted).length}`);
